"use client";

import Image from "next/image";
import { useEffect, useState } from "react";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { ArrowRight, Check, Clock3, RotateCcw, Star, Volume2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";

type PlaceId = "home" | "park" | "market" | "hospital" | "school" | "library" | "bank" | "restaurant" | "bus" | "supermarket";
type Place = { id: PlaceId; name: string; emoji: string; x: number; y: number; gridX: number; gridY: number; color: string };
type MissionProps = { finish: (points: number) => void };

const places: Place[] = [
  { id: "home", name: "Home", emoji: "🏠", x: 7, y: 76, gridX: 0, gridY: 3, color: "border-orange-300 bg-orange-100" },
  { id: "school", name: "School", emoji: "🏫", x: 7, y: 10, gridX: 0, gridY: 0, color: "border-yellow-300 bg-yellow-100" },
  { id: "park", name: "Park", emoji: "🌳", x: 30, y: 10, gridX: 1, gridY: 0, color: "border-emerald-300 bg-emerald-100" },
  { id: "library", name: "Library", emoji: "📚", x: 55, y: 10, gridX: 2, gridY: 0, color: "border-violet-300 bg-violet-100" },
  { id: "hospital", name: "Hospital", emoji: "🏥", x: 80, y: 10, gridX: 3, gridY: 0, color: "border-rose-300 bg-rose-100" },
  { id: "bus", name: "Bus Station", emoji: "🚌", x: 7, y: 43, gridX: 0, gridY: 1, color: "border-cyan-300 bg-cyan-100" },
  { id: "supermarket", name: "Supermarket", emoji: "🛍️", x: 80, y: 43, gridX: 3, gridY: 1, color: "border-fuchsia-300 bg-fuchsia-100" },
  { id: "market", name: "Market", emoji: "🛒", x: 30, y: 76, gridX: 1, gridY: 3, color: "border-amber-300 bg-amber-100" },
  { id: "bank", name: "Bank", emoji: "🏦", x: 55, y: 76, gridX: 2, gridY: 3, color: "border-sky-300 bg-sky-100" },
  { id: "restaurant", name: "Restaurant", emoji: "🍽️", x: 80, y: 76, gridX: 3, gridY: 3, color: "border-red-300 bg-red-100" }
];
const missions = ["City Detective", "Mystery Delivery", "Logic Route", "Direction Memory", "Sentence Workshop", "Race the Clock"];
const missionIcons = ["🔎", "📦", "🧠", "🧭", "🧩", "🏆"];

function place(id: PlaceId) { return places.find((item) => item.id === id)!; }
function sentence(id: PlaceId) { return `I go to the ${place(id).name.toLowerCase()}.`; }
function speak(text: string) { if (!("speechSynthesis" in window)) return; window.speechSynthesis.cancel(); const voice = new SpeechSynthesisUtterance(text); voice.lang = "en-US"; voice.rate = 0.78; window.speechSynthesis.speak(voice); }
function shuffle<T>(items: T[]) { const result = [...items]; for (let index = result.length - 1; index > 0; index -= 1) { const target = Math.floor(Math.random() * (index + 1)); [result[index], result[target]] = [result[target], result[index]]; } return result; }
function distance(from: PlaceId, to: PlaceId) { const a = place(from); const b = place(to); return Math.abs(a.gridX - b.gridX) + Math.abs(a.gridY - b.gridY); }

export function PublicPlacesAdventure() {
  const reduceMotion = useReducedMotion(); const [started, setStarted] = useState(false); const [mission, setMission] = useState(0); const [score, setScore] = useState(0); const [completed, setCompleted] = useState<number[]>([]); const [celebrating, setCelebrating] = useState(false);
  function finish(points: number) { if (celebrating) return; setScore((value) => value + points); setCompleted((value) => [...value, mission]); setCelebrating(true); window.setTimeout(() => { setMission((value) => value + 1); setCelebrating(false); }, 1000); }
  function reset() { setStarted(false); setMission(0); setScore(0); setCompleted([]); setCelebrating(false); }
  if (!started) return <Card className="relative overflow-hidden border-0 bg-[linear-gradient(145deg,#0f172a,#1d4ed8)] p-6 text-white shadow-soft sm:p-10"><div className="absolute -right-16 -top-16 h-64 w-64 rounded-full bg-yellow-300/20" /><motion.div animate={reduceMotion ? {} : { y: [0, -7, 0] }} transition={{ duration: 2.5, repeat: Infinity }} className="relative flex items-center gap-4"><Image src="/images/brand-icon-cropped.png" alt="Wisey the Owl" width={90} height={90} className="rounded-2xl bg-white p-2" /><span className="text-7xl">🗺️</span></motion.div><p className="relative mt-6 font-bold uppercase tracking-[0.18em] text-yellow-300">LEAD · Speak English with Confidence</p><h2 className="relative mt-3 font-heading text-4xl font-extrabold sm:text-5xl">City Mission Control</h2><p className="relative mt-4 max-w-2xl text-lg leading-8 text-blue-50">Wisey needs a smart city partner. Read clues, solve routes, remember directions, and use English to finish six connected missions. Think before you travel!</p><Button onClick={() => setStarted(true)} className="relative mt-7 bg-yellow-400 text-slate-950 hover:bg-yellow-300">Accept the challenge <ArrowRight className="h-4 w-4" /></Button></Card>;
  if (mission >= missions.length) return <Results score={score} reset={reset} />;
  return <div className="grid gap-4"><MissionProgress mission={mission} score={score} completed={completed} /><Card className="relative overflow-hidden p-3 sm:p-5"><AnimatePresence>{celebrating ? <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="absolute inset-0 z-50 grid place-items-center bg-white/95 p-6 text-center backdrop-blur"><motion.div initial={{ scale: .5 }} animate={{ scale: 1 }}><div className="text-7xl">⭐</div><h2 className="mt-3 font-heading text-3xl font-extrabold text-lead-navy">Mission solved!</h2><p className="mt-2 font-semibold text-lead-gray">Wisey is preparing your next city challenge.</p></motion.div></motion.div> : null}</AnimatePresence>{mission === 0 && <CityDetective finish={finish} />}{mission === 1 && <MysteryDelivery finish={finish} />}{mission === 2 && <LogicRoute finish={finish} />}{mission === 3 && <DirectionMemory finish={finish} />}{mission === 4 && <SentenceWorkshop finish={finish} />}{mission === 5 && <RaceTheClock finish={finish} />}</Card></div>;
}

function MissionProgress({ mission, score, completed }: { mission: number; score: number; completed: number[] }) { return <Card className="p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-sky-700">Challenge {mission + 1} of 6</p><h2 className="font-heading text-xl font-extrabold text-lead-navy">{missions[mission]}</h2></div><span className="rounded-full bg-yellow-50 px-4 py-2 font-bold text-yellow-800">⭐ {score}</span></div><div className="mt-4 flex gap-2">{missionIcons.map((icon, index) => <div key={icon} className={`grid h-10 flex-1 place-items-center rounded-lg ${completed.includes(index) ? "bg-emerald-500 text-white" : index === mission ? "bg-yellow-300 ring-2 ring-yellow-100" : "bg-slate-100 grayscale"}`}>{completed.includes(index) ? "✓" : icon}</div>)}</div></Card>; }
function MissionBoard({ title, guide, message, active = "home", markerPosition, targets = [], visited = [], onVisit, children }: { title: string; guide: string; message: string; active?: PlaceId; markerPosition?: { x: number; y: number }; targets?: PlaceId[]; visited?: PlaceId[]; onVisit?: (id: PlaceId) => void; children: React.ReactNode }) { return <div><div className="mb-4 flex items-start gap-3 rounded-2xl bg-sky-50 p-4"><Image src="/images/brand-icon-cropped.png" alt="Wisey" width={45} height={45} className="rounded-xl bg-white p-1" /><div><p className="text-xs font-bold uppercase tracking-[0.12em] text-sky-700">{guide}</p><h3 className="font-heading text-lg font-extrabold text-lead-navy">{title}</h3><p className="mt-1 text-sm leading-6 text-lead-gray">{message}</p></div></div><div className="grid items-start gap-4 xl:grid-cols-[minmax(0,1.25fr)_minmax(310px,.75fr)]"><CityMap active={active} markerPosition={markerPosition} targets={targets} visited={visited} onVisit={onVisit} /><aside className="rounded-2xl border border-slate-200 bg-slate-50 p-4">{children}</aside></div></div>; }
function CityMap({ active, markerPosition, targets, visited, onVisit }: { active: PlaceId; markerPosition?: { x: number; y: number }; targets: PlaceId[]; visited: PlaceId[]; onVisit?: (id: PlaceId) => void }) { const markerLeft = markerPosition ? [7, 30, 55, 80][markerPosition.x] + 5 : place(active).x + 5; const markerTop = markerPosition ? [10, 32, 54, 76][markerPosition.y] - 9 : place(active).y - 9; return <div className="relative mx-auto aspect-[16/11] w-full overflow-hidden rounded-3xl border-4 border-sky-100 bg-[#dff3d8] shadow-inner"><div className="absolute left-0 right-0 top-[31%] h-[13%] bg-slate-300"><div className="absolute left-0 right-0 top-1/2 border-t-2 border-dashed border-white" /></div><div className="absolute bottom-[21%] left-0 right-0 h-[13%] bg-slate-300"><div className="absolute left-0 right-0 top-1/2 border-t-2 border-dashed border-white" /></div><div className="absolute bottom-0 left-[22%] top-0 w-[9%] bg-slate-300"><div className="absolute bottom-0 left-1/2 top-0 border-l-2 border-dashed border-white" /></div><div className="absolute bottom-0 left-[70%] top-0 w-[9%] bg-slate-300"><div className="absolute bottom-0 left-1/2 top-0 border-l-2 border-dashed border-white" /></div><motion.span animate={{ x: [0, 140, 280, 140, 0] }} transition={{ repeat: Infinity, duration: 12 }} className="absolute left-[28%] top-[35%] z-10 text-xl sm:text-3xl">🚗</motion.span>{places.map((item) => <motion.button key={item.id} type="button" whileTap={{ scale: .9 }} onClick={() => onVisit?.(item.id)} style={{ left: `${item.x}%`, top: `${item.y}%` }} className={`absolute z-20 w-[13%] min-w-11 -translate-y-1/2 rounded-xl border-2 p-1 text-center shadow-sm sm:p-2 ${item.color} ${targets.includes(item.id) ? "ring-4 ring-yellow-300" : ""}`}><span className="block text-xl sm:text-3xl">{item.emoji}</span><span className="hidden text-[9px] font-black uppercase text-lead-navy sm:block">{item.name}</span>{visited.includes(item.id) ? <span className="absolute -right-1 -top-1 grid h-5 w-5 place-items-center rounded-full bg-emerald-500 text-[10px] text-white">✓</span> : null}</motion.button>)}<motion.div layout style={{ left: `${markerLeft}%`, top: `${markerTop}%` }} className="absolute z-30 text-2xl sm:text-4xl">🦉</motion.div><span className="absolute bottom-1 left-1 rounded-lg bg-white/90 px-2 py-1 text-[9px] font-bold text-sky-800 sm:text-xs">Tap buildings to move Wisey</span></div>; }

const detectiveClues = [
  { answer: "library" as PlaceId, clue: "I need a quiet place where I can borrow a book, but I do not want to buy it.", keywords: "quiet · borrow · book" },
  { answer: "bank" as PlaceId, clue: "My wallet is empty. I need to withdraw money before I shop.", keywords: "money · withdraw · account" },
  { answer: "bus" as PlaceId, clue: "I have no car, and I need public transport to another town.", keywords: "ticket · passengers · transport" },
  { answer: "supermarket" as PlaceId, clue: "I need rice, soap, milk, and vegetables from one large shop.", keywords: "many products · trolley · checkout" }
];
function CityDetective({ finish }: MissionProps) {
  const [round, setRound] = useState(0); const [active, setActive] = useState<PlaceId>("home"); const [solved, setSolved] = useState<PlaceId[]>([]); const [message, setMessage] = useState("No building name is given in the clue. Read carefully and choose the best place on the map."); const [mistakes, setMistakes] = useState(0); const current = detectiveClues[round];
  function visit(id: PlaceId) { setActive(id); if (id !== current.answer) { setMistakes((value) => value + 1); setMessage("That place cannot complete every part of the clue. Compare the key words and think again."); return; } const next = [...solved, id]; setSolved(next); speak(`${place(id).name}. ${sentence(id)}`); if (round === detectiveClues.length - 1) finish(Math.max(8, 12 - mistakes)); else { setRound((value) => value + 1); setMessage("Correct deduction. Read the next city clue."); } }
  return <MissionBoard title="Find the place from evidence" guide="Challenge 1 · Inference" message={message} active={active} visited={solved} onVisit={visit}><p className="text-xs font-bold uppercase tracking-wider text-sky-700">Case {round + 1} / {detectiveClues.length}</p><blockquote className="mt-3 rounded-2xl bg-white p-4 font-heading text-lg font-bold leading-7 text-lead-navy shadow-sm">“{current.clue}”</blockquote><p className="mt-4 text-xs font-bold text-lead-gray">Evidence: {current.keywords}</p><p className="mt-5 rounded-xl bg-blue-50 p-3 text-sm font-semibold text-blue-800">Which building solves the whole problem? Tap it on the map.</p></MissionBoard>;
}

const parcels = [
  { id: "parcel-a", icon: "📦 A", contents: "A storybook, a dictionary, and a return card", destination: "library" as PlaceId },
  { id: "parcel-b", icon: "📦 B", contents: "A bandage, medicine, and a patient form", destination: "hospital" as PlaceId },
  { id: "parcel-c", icon: "📦 C", contents: "Coins, a signed form, and an account book", destination: "bank" as PlaceId }
];
function MysteryDelivery({ finish }: MissionProps) {
  const [selected, setSelected] = useState(""); const [done, setDone] = useState<string[]>([]); const [active, setActive] = useState<PlaceId>("home"); const [message, setMessage] = useState("The address labels are missing. Inspect each parcel, then deliver it to the place that uses all its contents."); const [attempts, setAttempts] = useState(0);
  function visit(id: PlaceId) { if (!selected) { setMessage("Select and inspect a parcel before travelling."); return; } setActive(id); const parcel = parcels.find((item) => item.id === selected)!; if (id !== parcel.destination) { setAttempts((value) => value + 1); setMessage("The staff here would not use all those objects. Re-read the parcel contents."); return; } const next = [...done, selected]; setDone(next); setSelected(""); speak(`Package delivered to the ${place(id).name}.`); setMessage(`Delivery accepted. ${sentence(id)}`); if (next.length === parcels.length) finish(Math.max(8, 12 - attempts)); }
  return <MissionBoard title="Recover the missing addresses" guide="Challenge 2 · Classification" message={message} active={active} visited={parcels.filter((item) => done.includes(item.id)).map((item) => item.destination)} onVisit={visit}><div className="grid gap-3">{parcels.map((parcel) => <button key={parcel.id} disabled={done.includes(parcel.id)} onClick={() => setSelected(parcel.id)} className={`rounded-2xl border-2 bg-white p-4 text-left disabled:opacity-40 ${selected === parcel.id ? "border-lead-blue ring-4 ring-blue-100" : "border-slate-200"}`}><span className="font-heading text-xl font-extrabold text-lead-navy">{done.includes(parcel.id) ? "✓ Delivered" : parcel.icon}</span><span className="mt-2 block text-sm leading-6 text-lead-gray">Inside: {parcel.contents}</span></button>)}</div></MissionBoard>;
}

function LogicRoute({ finish }: MissionProps) {
  const destinations: PlaceId[] = ["market", "park", "library", "hospital"]; const correct: PlaceId[] = ["library", "market", "park", "hospital"]; const [route, setRoute] = useState<PlaceId[]>([]); const [message, setMessage] = useState("Create one route that obeys all four rules. A place can only be used once."); const [attempts, setAttempts] = useState(0);
  function add(id: PlaceId) { if (!destinations.includes(id) || route.includes(id)) return; setRoute((value) => [...value, id]); }
  function check() { if (route.length !== 4) return; if (route.join() !== correct.join()) { setAttempts((value) => value + 1); setMessage("At least one rule is broken. Find the conflict, reset, and revise your route."); return; } route.forEach((id, index) => window.setTimeout(() => speak(sentence(id)), index * 650)); finish(Math.max(8, 12 - attempts)); }
  return <MissionBoard title="Build a route from logic clues" guide="Challenge 3 · Planning" message={message} active={route.at(-1) || "home"} targets={destinations.filter((id) => !route.includes(id))} visited={route} onVisit={add}><ol className="grid gap-2 text-sm font-semibold text-lead-navy"><li className="rounded-xl bg-white p-3">1. Borrow the book before spending money.</li><li className="rounded-xl bg-white p-3">2. The market is immediately before the park.</li><li className="rounded-xl bg-white p-3">3. The hospital is the final stop.</li><li className="rounded-xl bg-white p-3">4. Do not visit the park first.</li></ol><div className="mt-4 flex min-h-16 flex-wrap items-center gap-2 rounded-xl bg-blue-50 p-3"><span className="font-bold">🏠</span>{route.map((id) => <span key={id} className="font-bold text-lead-navy">→ {place(id).emoji} {place(id).name}</span>)}</div><div className="mt-4 flex gap-2"><Button variant="secondary" onClick={() => setRoute([])}><RotateCcw className="h-4 w-4" />Reset</Button><Button disabled={route.length !== 4} onClick={check}><Check className="h-4 w-4" />Test route</Button></div></MissionBoard>;
}

type Direction = { dx: number; dy: number; label: string; icon: string };
const directionPlan: Direction[] = [{ dx: 1, dy: 0, label: "Go east", icon: "➡️" }, { dx: 1, dy: 0, label: "Go east", icon: "➡️" }, { dx: 0, dy: -1, label: "Go north", icon: "⬆️" }, { dx: 0, dy: -1, label: "Go north", icon: "⬆️" }, { dx: 0, dy: -1, label: "Go north", icon: "⬆️" }, { dx: 1, dy: 0, label: "Go east", icon: "➡️" }];
function DirectionMemory({ finish }: MissionProps) {
  const [preview, setPreview] = useState(true); const [seconds, setSeconds] = useState(6); const [position, setPosition] = useState({ x: 0, y: 3 }); const [step, setStep] = useState(0); const [message, setMessage] = useState("Study the route. It will disappear in six seconds."); const [mistakes, setMistakes] = useState(0);
  useEffect(() => { if (!preview) return; const timer = window.setInterval(() => setSeconds((value) => { if (value <= 1) { window.clearInterval(timer); setPreview(false); setMessage("The directions are hidden. Recreate the route from memory."); return 0; } return value - 1; }), 1000); return () => window.clearInterval(timer); }, [preview]);
  function move(direction: Direction) { if (preview) return; const expected = directionPlan[step]; if (direction.dx !== expected.dx || direction.dy !== expected.dy) { setMistakes((value) => value + 1); setMessage("That was not the next direction. Your position has not changed; recall the route."); return; } const next = { x: position.x + direction.dx, y: position.y + direction.dy }; setPosition(next); setStep((value) => value + 1); speak(direction.label); if (step === directionPlan.length - 1) { speak("You found the hospital."); finish(Math.max(8, 12 - mistakes)); } }
  const controls = [{ dx: 0, dy: -1, label: "Go north", icon: "⬆️" }, { dx: -1, dy: 0, label: "Go west", icon: "⬅️" }, { dx: 0, dy: 1, label: "Go south", icon: "⬇️" }, { dx: 1, dy: 0, label: "Go east", icon: "➡️" }]; const activePlace = places.find((item) => item.gridX === position.x && item.gridY === position.y)?.id || "home";
  return <MissionBoard title="Remember Wisey's directions" guide="Challenge 4 · Working memory" message={message} active={activePlace} markerPosition={position} targets={preview ? ["hospital"] : []} visited={[]}><div className="rounded-2xl bg-white p-4 text-center"><p className="text-xs font-bold uppercase tracking-wider text-sky-700">Home to Hospital</p>{preview ? <><p className="mt-3 text-3xl">{directionPlan.map((item) => item.icon).join(" ")}</p><p className="mt-3 font-heading text-2xl font-extrabold text-rose-600">Hiding in {seconds}s</p></> : <><p className="mt-3 text-sm font-bold text-lead-gray">Direction {step + 1} of {directionPlan.length}</p><div className="mt-4 grid grid-cols-2 gap-2">{controls.map((item) => <button key={item.label} onClick={() => move(item)} className="rounded-xl bg-lead-blue p-3 font-bold text-white"><span className="text-2xl">{item.icon}</span><span className="block text-xs">{item.label}</span></button>)}</div></>}</div></MissionBoard>;
}

const sentenceRounds = [
  { destination: "market" as PlaceId, prompt: "Tell Wisey where you regularly buy fruit.", words: ["I", "go", "to", "the", "market.", "am", "hospital", "at"] },
  { destination: "park" as PlaceId, prompt: "Tell your friend where you are going now.", words: ["I", "am", "going", "to", "the", "park.", "goes", "bank", "from"] },
  { destination: "hospital" as PlaceId, prompt: "Ask for help because your friend is sick.", words: ["I", "need", "to", "go", "to", "the", "hospital.", "park", "going", "are"] }
];
function SentenceWorkshop({ finish }: MissionProps) {
  const [round, setRound] = useState(0); const [answer, setAnswer] = useState<string[]>([]); const [pool, setPool] = useState(() => shuffle(sentenceRounds[0].words)); const [message, setMessage] = useState("Some words are distractors. Build the most natural sentence for the situation."); const [attempts, setAttempts] = useState(0); const current = sentenceRounds[round]; const targets = round === 0 ? ["I", "go", "to", "the", "market."] : round === 1 ? ["I", "am", "going", "to", "the", "park."] : ["I", "need", "to", "go", "to", "the", "hospital."];
  function add(word: string, index: number) { setAnswer((value) => [...value, word]); setPool((value) => value.filter((_, position) => position !== index)); }
  function resetWords() { setAnswer([]); setPool(shuffle(current.words)); }
  function check() { if (answer.join(" ") !== targets.join(" ")) { setAttempts((value) => value + 1); setMessage("The meaning or grammar is not quite right. Remove the distractors and check the word order."); resetWords(); return; } speak(answer.join(" ")); if (round === sentenceRounds.length - 1) { finish(Math.max(9, 15 - attempts)); return; } const next = round + 1; setRound(next); setAnswer([]); setPool(shuffle(sentenceRounds[next].words)); setMessage("Strong sentence. Now choose the language that fits the next situation."); }
  return <MissionBoard title="Say exactly what the situation needs" guide="Challenge 5 · Language construction" message={message} active={current.destination} targets={[current.destination]} visited={sentenceRounds.slice(0, round).map((item) => item.destination)}><p className="rounded-2xl bg-white p-4 font-heading text-lg font-bold leading-7 text-lead-navy">{current.prompt}</p><div className="mt-4 flex min-h-24 flex-wrap content-center gap-2 rounded-2xl border-4 border-dashed border-blue-200 bg-blue-50 p-3">{answer.length ? answer.map((word, index) => <span key={`${word}-${index}`} className="rounded-xl bg-lead-blue px-3 py-2 font-bold text-white">{word}</span>) : <span className="text-sm font-bold text-blue-500">Build your sentence here</span>}</div><div className="mt-4 flex flex-wrap gap-2">{pool.map((word, index) => <button key={`${word}-${index}`} onClick={() => add(word, index)} className="rounded-xl border-2 border-slate-200 bg-white px-3 py-2 font-bold text-lead-navy">{word}</button>)}</div><div className="mt-4 flex gap-2"><Button variant="secondary" onClick={resetWords}><RotateCcw className="h-4 w-4" />Reset</Button><Button disabled={!answer.length} onClick={check}><Check className="h-4 w-4" />Check meaning</Button><Button size="sm" variant="secondary" onClick={() => speak(targets.join(" "))}><Volume2 className="h-4 w-4" /></Button></div></MissionBoard>;
}

const finalTasks = [
  { id: "medicine", place: "hospital" as PlaceId, label: "Collect medicine before the hospital closes", closes: 7 },
  { id: "cash", place: "bank" as PlaceId, label: "Withdraw money before buying fruit", closes: 12 },
  { id: "fruit", place: "market" as PlaceId, label: "Buy fruit before meeting your friend", closes: 16 },
  { id: "friend", place: "park" as PlaceId, label: "Meet your friend before dinner", closes: 20 },
  { id: "dinner", place: "restaurant" as PlaceId, label: "Eat dinner after meeting your friend", closes: 24 }
];
function RaceTheClock({ finish }: MissionProps) {
  const [active, setActive] = useState<PlaceId>("home"); const [time, setTime] = useState(0); const [done, setDone] = useState<string[]>([]); const [message, setMessage] = useState("Each road block costs one minute. Work out an efficient route and obey every condition."); const [restarts, setRestarts] = useState(0);
  function resetRun() { setActive("home"); setTime(0); setDone([]); setRestarts((value) => value + 1); setMessage("Plan a better route. Watch closing times and task dependencies."); }
  function visit(id: PlaceId) { const task = finalTasks.find((item) => item.place === id && !done.includes(item.id)); if (!task) { setMessage("There is no unfinished task at that building. Avoid wasting travel time."); return; } const arrival = time + distance(active, id); if (arrival > task.closes) { setMessage(`${place(id).name} is closed at minute ${task.closes}. Your arrival would be minute ${arrival}. Restart and change the order.`); return; } if (task.id === "fruit" && !done.includes("cash")) { setMessage("You need money from the bank before buying fruit."); return; } if (task.id === "friend" && !done.includes("fruit")) { setMessage("Buy the fruit before meeting your friend."); return; } if (task.id === "dinner" && (!done.includes("cash") || !done.includes("friend"))) { setMessage("You need money and must meet your friend before dinner."); return; } const next = [...done, task.id]; setDone(next); setActive(id); setTime(arrival); speak(sentence(id)); setMessage(`${task.label} — completed at minute ${arrival}.`); if (next.length === finalTasks.length) finish(Math.max(12, 20 - restarts * 2)); }
  return <MissionBoard title="Finish the city day before time runs out" guide="Final challenge · Strategy" message={message} active={active} targets={finalTasks.filter((item) => !done.includes(item.id)).map((item) => item.place)} visited={finalTasks.filter((item) => done.includes(item.id)).map((item) => item.place)} onVisit={visit}><div className="flex items-center justify-between rounded-2xl bg-lead-navy p-4 text-white"><span className="inline-flex items-center gap-2 font-bold"><Clock3 className="h-5 w-5" />Time used</span><span className="font-heading text-2xl font-extrabold">{time} / 24 min</span></div><div className="mt-4 grid gap-2">{finalTasks.map((task) => <div key={task.id} className={`rounded-xl border p-3 text-sm ${done.includes(task.id) ? "border-emerald-300 bg-emerald-50 text-emerald-800" : "border-slate-200 bg-white text-lead-navy"}`}><span className="font-bold">{done.includes(task.id) ? "✓" : place(task.place).emoji} {task.label}</span><span className="mt-1 block text-xs">Closes at minute {task.closes}</span></div>)}</div><Button variant="secondary" className="mt-4 w-full" onClick={resetRun}><RotateCcw className="h-4 w-4" />Restart route</Button></MissionBoard>;
}

function Results({ score, reset }: { score: number; reset: () => void }) { const stars = Math.max(3, Math.min(5, Math.ceil(score / 15))); return <Card className="overflow-hidden border-yellow-200 bg-[linear-gradient(145deg,#eff6ff,#ffffff,#fef3c7)] p-6 text-center shadow-soft sm:p-10"><motion.div initial={{ scale: 0 }} animate={{ scale: 1 }} className="text-8xl">🏆</motion.div><p className="mt-5 font-bold uppercase tracking-[0.18em] text-sky-700">City Mission Complete</p><h2 className="mt-2 font-heading text-4xl font-extrabold text-lead-navy">Master City Explorer</h2><p className="mt-3 text-lg text-lead-gray">You used clues, memory, logic, planning, and English to solve the whole city.</p><div className="mt-6 flex justify-center gap-1">{[1,2,3,4,5].map((number) => <Star key={number} className={`h-9 w-9 ${number <= stars ? "fill-yellow-400 text-yellow-500" : "text-slate-300"}`} />)}</div><div className="mx-auto mt-7 grid max-w-3xl gap-3 sm:grid-cols-3"><Result label="Challenges" value="6 / 6" /><Result label="Thinking score" value={`${score} points`} /><Result label="Language" value="Confident" /></div><div className="mt-7 flex flex-wrap justify-center gap-3"><Button onClick={reset}><RotateCcw className="h-4 w-4" />Play Again</Button><Button asChild variant="secondary"><a href="/games">Back to LEAD Games</a></Button></div></Card>; }
function Result({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-wider text-slate-500">{label}</p><p className="mt-2 font-heading text-xl font-extrabold text-lead-navy">{value}</p></div>; }
