"use client";

import { useEffect, useMemo, useState } from "react";
import { Eye, Lightbulb, RotateCcw, Undo2, Volume2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { arcadeSound, speakArcade } from "../lead-arcade/audio";
import type { ArcadeStageProps } from "../lead-arcade/types";
import { clothes, detectiveRounds, runwayRounds, scrabbleWords, studioMissions } from "./game-data";

function result(correct: number, attempts: number, score: number, combo: number, practiced: string[]) { return { correct, attempts, score, bestCombo: combo, stars: correct / Math.max(1, attempts) >= .85 ? 3 : correct / Math.max(1, attempts) >= .6 ? 2 : 1, practiced }; }

export function ClosetHunt({ sound, onComplete }: ArcadeStageProps) {
  const [round, setRound] = useState(0); const [correct, setCorrect] = useState(0); const [attempts, setAttempts] = useState(0); const [combo, setCombo] = useState(0); const [best, setBest] = useState(0); const [feedback, setFeedback] = useState("");
  const targets = [clothes[2], clothes[5], clothes[0], clothes[6]]; const target = targets[round];
  const choices = useMemo(() => [target, clothes[(round + 1) % clothes.length], clothes[(round + 4) % clothes.length], clothes[(round + 6) % clothes.length]].filter((item, index, list) => list.findIndex((other) => other.word === item.word) === index), [round, target]);
  function choose(word: string) { const nextAttempts = attempts + 1; setAttempts(nextAttempts); if (word !== target.word) { setCombo(0); setFeedback("Not that one—listen to the clothing word again!"); arcadeSound("wrong", sound); return; } const nextCorrect = correct + 1; const nextCombo = combo + 1; setCorrect(nextCorrect); setCombo(nextCombo); setBest(Math.max(best, nextCombo)); setFeedback(`Yes! It is a ${target.color} ${target.word}.`); arcadeSound("correct", sound); setTimeout(() => { if (round === targets.length - 1) onComplete(result(nextCorrect, nextAttempts, nextCorrect * 250, Math.max(best, nextCombo), targets.map((item) => item.word))); else { setRound((value) => value + 1); setFeedback(""); } }, 650); }
  return <GameFrame title="Closet Hunt" badge={`${round + 1}/4`}><div className="text-center"><p className="text-sm font-black uppercase tracking-widest text-yellow-300">Find it fast</p><h3 className="mt-3 text-2xl font-black">Find the <span className="text-yellow-300">{target.color} {target.word}</span></h3><Button onClick={() => speakArcade(`Find the ${target.color} ${target.word}`, sound)} className="mt-3" variant="secondary"><Volume2 className="h-4 w-4" />Listen</Button></div><div className="mx-auto mt-8 grid max-w-3xl grid-cols-2 gap-4 sm:grid-cols-4">{choices.map((item) => <button key={item.word} onClick={() => choose(item.word)} className="focus-ring rounded-[2rem] border-4 border-white/10 bg-white/10 p-5 transition hover:-translate-y-2 hover:border-yellow-300"><span className="block text-7xl">{item.emoji}</span><span className="mt-3 block font-black capitalize">{item.word}</span></button>)}</div><Feedback text={feedback} /></GameFrame>;
}

export function WordTailor({ sound, onComplete }: ArcadeStageProps) {
  const [round, setRound] = useState(0); const [picked, setPicked] = useState<number[]>([]); const [attempts, setAttempts] = useState(0); const [correct, setCorrect] = useState(0); const [combo, setCombo] = useState(0); const [best, setBest] = useState(0); const [feedback, setFeedback] = useState("");
  const word = scrabbleWords[round]; const letters = useMemo(() => word.split("").map((letter, index) => ({ letter, original: index })).sort((a, b) => ((a.original * 7 + round * 3) % 11) - ((b.original * 7 + round * 3) % 11)), [word, round]); const built = picked.map((index) => letters[index].letter).join("");
  function check() { const nextAttempts = attempts + 1; setAttempts(nextAttempts); if (built !== word) { setCombo(0); setFeedback("The tailor dropped the letters! Rearrange them and try again."); arcadeSound("wrong", sound); return; } const nextCorrect = correct + 1; const nextCombo = combo + 1; setCorrect(nextCorrect); setCombo(nextCombo); setBest(Math.max(best, nextCombo)); setFeedback(`Perfect spelling: ${word.toUpperCase()}!`); arcadeSound("correct", sound); setTimeout(() => { if (round === scrabbleWords.length - 1) onComplete(result(nextCorrect, nextAttempts, nextCorrect * 300, Math.max(best, nextCombo), scrabbleWords)); else { setRound((value) => value + 1); setPicked([]); setFeedback(""); } }, 650); }
  return <GameFrame title="Word Tailor Scrabble" badge={`${round + 1}/5`}><div className="text-center"><p className="text-sm font-black uppercase tracking-widest text-yellow-300">Sew the word together</p><div className="mt-3 text-7xl">{clothes.find((item) => item.word === word)?.emoji}</div><p className="mt-3 font-bold text-fuchsia-100">Tap every tile in the correct spelling order.</p></div><div className="mt-7 flex min-h-20 flex-wrap justify-center gap-2 rounded-2xl border-2 border-dashed border-fuchsia-300/50 bg-black/20 p-4">{built ? picked.map((tile, index) => <span key={`${tile}-${index}`} className="grid h-14 w-14 place-items-center rounded-lg border-b-4 border-amber-700 bg-yellow-200 text-2xl font-black text-slate-900">{letters[tile].letter.toUpperCase()}</span>) : <span className="self-center font-bold text-fuchsia-200">Your word appears here</span>}</div><div className="mt-5 flex flex-wrap justify-center gap-3">{letters.map((tile, index) => <button key={`${tile.original}-${tile.letter}`} disabled={picked.includes(index)} onClick={() => setPicked((value) => [...value, index])} className="focus-ring grid h-16 w-16 place-items-center rounded-xl border-b-4 border-fuchsia-900 bg-white text-3xl font-black text-fuchsia-900 shadow-lg disabled:opacity-20">{tile.letter.toUpperCase()}<small className="absolute ml-10 mt-10 text-[9px]">1</small></button>)}</div><div className="mt-5 flex justify-center gap-2"><Button variant="secondary" onClick={() => setPicked((value) => value.slice(0, -1))} disabled={!picked.length}><Undo2 className="h-4 w-4" />Undo</Button><Button variant="secondary" onClick={() => setPicked([])}><RotateCcw className="h-4 w-4" />Reset</Button><Button onClick={check} disabled={picked.length !== letters.length}>CHECK WORD</Button></div><Feedback text={feedback} /></GameFrame>;
}

export function StyleDetective({ sound, onComplete }: ArcadeStageProps) {
  const [round, setRound] = useState(0); const [attempts, setAttempts] = useState(0); const [correct, setCorrect] = useState(0); const [combo, setCombo] = useState(0); const [best, setBest] = useState(0); const [feedback, setFeedback] = useState(""); const item = detectiveRounds[round];
  function choose(choice: string) { const nextAttempts = attempts + 1; setAttempts(nextAttempts); if (choice !== item.answer) { setCombo(0); setFeedback("Check every color and clothing item."); arcadeSound("wrong", sound); return; } const nextCorrect = correct + 1; const nextCombo = combo + 1; setCorrect(nextCorrect); setCombo(nextCombo); setBest(Math.max(best, nextCombo)); setFeedback("Case solved! That sentence matches the outfit."); arcadeSound("correct", sound); setTimeout(() => { if (round === detectiveRounds.length - 1) onComplete(result(nextCorrect, nextAttempts, nextCorrect * 275, Math.max(best, nextCombo), ["I'm wearing…", "She is wearing…", "He is wearing…"])); else { setRound((value) => value + 1); setFeedback(""); } }, 650); }
  return <GameFrame title="Style Detective" badge={`Case ${round + 1}/4`}><div className="mx-auto max-w-3xl text-center"><div className="rounded-[2rem] bg-[linear-gradient(135deg,#fdf2f8,#fef3c7)] p-8 text-slate-900"><Eye className="mx-auto h-7 w-7 text-fuchsia-700" /><div className="mt-3 text-8xl">{item.look}</div><p className="mt-3 text-sm font-black uppercase tracking-widest text-fuchsia-700">Evidence: {item.clue}</p></div><div className="mt-6 grid gap-3">{item.choices.map((choice) => <button key={choice} onClick={() => choose(choice)} className="focus-ring rounded-2xl border border-white/15 bg-white/10 p-4 text-left font-bold transition hover:border-yellow-300 hover:bg-white/20">{choice}</button>)}</div><Feedback text={feedback} /></div></GameFrame>;
}

export function OutfitStudio({ sound, onComplete }: ArcadeStageProps) {
  const [mission, setMission] = useState(0); const [selected, setSelected] = useState<string[]>([]); const [reason, setReason] = useState(""); const [attempts, setAttempts] = useState(0); const [correct, setCorrect] = useState(0); const [feedback, setFeedback] = useState(""); const current = studioMissions[mission];
  function toggle(word: string) { setSelected((value) => value.includes(word) ? value.filter((item) => item !== word) : value.length < 3 ? [...value, word] : value); }
  function submit() { const nextAttempts = attempts + 1; setAttempts(nextAttempts); const outfitCorrect = current.need.every((word) => selected.includes(word)) && selected.length === current.need.length && Boolean(reason); if (!outfitCorrect) { setFeedback("Use the mission clue: choose exactly three useful items and one reason."); arcadeSound("wrong", sound); return; } const nextCorrect = correct + 1; setCorrect(nextCorrect); const sentence = `I'm wearing ${selected.join(", ")} because it is ${reason}.`; setFeedback(sentence); speakArcade(sentence, sound); arcadeSound("correct", sound); setTimeout(() => { if (mission === studioMissions.length - 1) onComplete(result(nextCorrect, nextAttempts, nextCorrect * 450, nextCorrect, ["comfortable", "cool", "stylish"])); else { setMission(1); setSelected([]); setReason(""); setFeedback(""); } }, 1300); }
  return <GameFrame title="Outfit Studio" badge={`Design ${mission + 1}/2`}><div className="mx-auto max-w-4xl"><div className="rounded-2xl bg-yellow-300 p-5 text-center text-slate-950"><p className="text-xs font-black uppercase tracking-widest">Client mission</p><h3 className="mt-2 font-heading text-3xl font-black">{current.title}</h3><p className="mt-1 font-bold">Choose exactly 3 suitable items, then explain why.</p></div><div className="mt-5 grid grid-cols-4 gap-3 sm:grid-cols-8">{clothes.map((item) => <button key={item.word} onClick={() => toggle(item.word)} className={`focus-ring rounded-2xl border-2 p-3 text-center transition ${selected.includes(item.word) ? "border-yellow-300 bg-yellow-300 text-slate-950" : "border-white/10 bg-white/10 hover:border-fuchsia-300"}`}><span className="block text-4xl">{item.emoji}</span><span className="mt-1 block text-xs font-black capitalize">{item.word}</span></button>)}</div><div className="mt-6 rounded-2xl bg-white/10 p-5"><p className="font-black">I&apos;m wearing {selected.length ? selected.join(", ") : "…"} because it is…</p><div className="mt-3 flex flex-wrap gap-2">{["comfortable", "cool", "stylish"].map((item) => <button key={item} onClick={() => setReason(item)} className={`rounded-full px-4 py-2 text-sm font-black ${reason === item ? "bg-yellow-300 text-slate-950" : "bg-white/10"}`}>{item}</button>)}</div></div><Button onClick={submit} disabled={selected.length !== 3 || !reason} className="mt-5 w-full">SEND TO THE RUNWAY</Button><Feedback text={feedback} /></div></GameFrame>;
}

export function RunwayRecall({ sound, onComplete }: ArcadeStageProps) {
  const [round, setRound] = useState(0); const [show, setShow] = useState(true); const [attempts, setAttempts] = useState(0); const [correct, setCorrect] = useState(0); const [combo, setCombo] = useState(0); const [best, setBest] = useState(0); const [feedback, setFeedback] = useState(""); const item = runwayRounds[round];
  useEffect(() => { setShow(true); const timer = window.setTimeout(() => setShow(false), 3200); return () => window.clearTimeout(timer); }, [round]);
  function choose(choice: string) { const nextAttempts = attempts + 1; setAttempts(nextAttempts); if (choice !== item.answer) { setCombo(0); setFeedback("The runway lights flashed—remember the full outfit!"); arcadeSound("wrong", sound); return; } const nextCorrect = correct + 1; const nextCombo = combo + 1; setCorrect(nextCorrect); setCombo(nextCombo); setBest(Math.max(best, nextCombo)); setFeedback("Perfect runway recall!"); arcadeSound("correct", sound); setTimeout(() => { if (round === runwayRounds.length - 1) onComplete(result(nextCorrect, nextAttempts, nextCorrect * 500, Math.max(best, nextCombo), ["I'm wearing…", "because it is…"])); else { setRound((value) => value + 1); setFeedback(""); } }, 650); }
  return <GameFrame title="Runway Recall" badge={`Look ${round + 1}/3`}><div className="mx-auto max-w-3xl text-center"><div className="grid min-h-52 place-items-center rounded-[2rem] border border-fuchsia-300/30 bg-[radial-gradient(circle,#a21caf,#32124d_65%)] p-7">{show ? <div><p className="text-xs font-black uppercase tracking-[.3em] text-yellow-300">Memorize the outfit</p><div className="mt-5 text-8xl">{item.look}</div><p className="mt-4 font-bold">The curtain closes in 3 seconds!</p></div> : <div><div className="text-7xl">🎭</div><p className="mt-4 text-xl font-black">Which sentence described the outfit?</p></div>}</div>{!show ? <div className="mt-6 grid gap-3">{item.choices.map((choice) => <button key={choice} onClick={() => choose(choice)} className="focus-ring rounded-2xl border border-white/15 bg-white/10 p-4 text-left font-bold hover:border-yellow-300 hover:bg-white/20">{choice}</button>)}</div> : null}<Button variant="secondary" onClick={() => { setShow(true); window.setTimeout(() => setShow(false), 1800); }} className="mt-4"><Lightbulb className="h-4 w-4" />Quick peek</Button><Feedback text={feedback} /></div></GameFrame>;
}

function GameFrame({ title, badge, children }: { title: string; badge: string; children: React.ReactNode }) { return <section className="min-h-[600px]"><div className="flex items-center justify-between gap-3"><h2 className="font-heading text-2xl font-black">{title}</h2><span className="rounded-full bg-white/10 px-3 py-1 text-xs font-black uppercase text-yellow-300">{badge}</span></div><div className="mt-5">{children}</div></section>; }
function Feedback({ text }: { text: string }) { return <div aria-live="polite" className={`mx-auto mt-5 min-h-12 max-w-2xl rounded-xl px-4 py-3 text-center font-bold ${text ? "bg-white/10" : ""}`}>{text}</div>; }
