"use client";

import { Maximize2, Minimize2, RotateCcw, UserRound, Volume2, VolumeX } from "lucide-react";
import { Button } from "@/components/ui/button";
import { stageNames } from "./game-data";

export function ArcadeShell({ name, stage, stars, sound, fullscreen, onSound, onFullscreen, onChangeStudent, children }: { name: string; stage: number; stars: number; sound: boolean; fullscreen: boolean; onSound: () => void; onFullscreen: () => void; onChangeStudent: () => void; children: React.ReactNode }) {
  return <div id="family-adventure-shell" className="relative overflow-hidden rounded-[2rem] border border-blue-200 bg-[#07142e] text-white shadow-2xl fullscreen:rounded-none">
    <header className="relative z-40 flex flex-wrap items-center justify-between gap-3 border-b border-white/10 bg-[#0f172a]/95 px-4 py-3 sm:px-6">
      <div><p className="text-xs font-black uppercase tracking-[.2em] text-yellow-300">LEAD · Family Adventure</p><p className="text-sm font-bold text-blue-100">{name} · {stage < 5 ? `Challenge ${stage + 1}/5` : "Family Champion"}</p></div>
      <div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-yellow-400 px-3 py-1.5 text-sm font-black text-slate-950">⭐ {stars}/15</span><IconButton label={sound ? "Mute sound" : "Turn sound on"} onClick={onSound}>{sound ? <Volume2 /> : <VolumeX />}</IconButton><IconButton label={fullscreen ? "Exit fullscreen" : "Enter fullscreen"} onClick={onFullscreen}>{fullscreen ? <Minimize2 /> : <Maximize2 />}</IconButton><IconButton label="Change student" onClick={onChangeStudent}><UserRound /></IconButton></div>
    </header>
    <div className="relative z-30 grid grid-cols-5 border-b border-white/10 bg-white/5">{stageNames.map((title, index) => <div key={title} className={`px-1 py-2 text-center text-[10px] font-black uppercase sm:text-xs ${index <= stage ? "text-yellow-300" : "text-slate-500"}`}><span className={`mx-auto mb-1 grid h-6 w-6 place-items-center rounded-full ${index < stage ? "bg-emerald-500 text-white" : index === stage ? "bg-yellow-400 text-slate-950" : "bg-slate-700"}`}>{index < stage ? "✓" : index + 1}</span><span className="hidden sm:inline">{title}</span></div>)}</div>
    <main className="relative min-h-[650px] overflow-hidden p-4 sm:p-6">{children}</main>
  </div>;
}

function IconButton({ label, onClick, children }: { label: string; onClick: () => void; children: React.ReactNode }) { return <button type="button" aria-label={label} onClick={onClick} className="focus-ring grid h-9 w-9 place-items-center rounded-lg bg-white/10 text-white hover:bg-white/20 [&_svg]:h-4 [&_svg]:w-4">{children}</button>; }

export function StageIntro({ number, title, purpose, controls, emoji, onStart }: { number: number; title: string; purpose: string; controls: string; emoji: string; onStart: () => void }) {
  return <section className="mx-auto grid min-h-[590px] max-w-4xl place-items-center text-center"><div><div className="text-8xl animate-bounce" aria-hidden="true">{emoji}</div><p className="mt-5 text-sm font-black uppercase tracking-[.28em] text-yellow-300">Challenge {number}</p><h2 className="mt-3 font-heading text-5xl font-black sm:text-7xl">{title}</h2><p className="mx-auto mt-4 max-w-2xl text-lg font-bold leading-8 text-blue-100">{purpose}</p><div className="mx-auto mt-6 max-w-xl rounded-2xl border border-white/15 bg-white/10 px-5 py-4 text-sm font-bold text-white">Controls: {controls}</div><Button onClick={onStart} className="mt-7 h-14 bg-yellow-400 px-10 text-base font-black text-slate-950 hover:bg-yellow-300">START CHALLENGE</Button></div></section>;
}

export function StageComplete({ title, result, onContinue }: { title: string; result: { stars: number; score: number; correct: number; attempts: number; bestCombo: number }; onContinue: () => void }) {
  const accuracy = Math.round((result.correct / Math.max(1, result.attempts)) * 100);
  return <section className="absolute inset-0 z-50 grid place-items-center bg-[#07142e]/95 p-5 text-center"><div className="w-full max-w-lg rounded-[2rem] border-4 border-yellow-300 bg-white p-7 text-slate-900 shadow-2xl"><div className="text-5xl">{Array.from({ length: 3 }, (_, index) => <span key={index} className={index < result.stars ? "" : "grayscale opacity-25"}>⭐</span>)}</div><p className="mt-4 text-sm font-black uppercase tracking-[.2em] text-blue-600">Stage complete!</p><h2 className="mt-2 font-heading text-4xl font-black text-slate-900">{title}</h2><div className="mt-5 grid grid-cols-3 gap-3"><Stat label="Score" value={result.score.toLocaleString()} /><Stat label="Accuracy" value={`${accuracy}%`} /><Stat label="Combo" value={`x${result.bestCombo}`} /></div><p className="mt-6 font-black text-emerald-700">🔓 NEXT STAGE UNLOCKED</p><Button onClick={onContinue} className="mt-5 w-full">CONTINUE ADVENTURE</Button></div></section>;
}

export function FinalResults({ name, results, onReplay, onChange }: { name: string; results: Array<{ stars: number; score: number; correct: number; attempts: number; bestCombo: number; sentences?: string[] }>; onReplay: () => void; onChange: () => void }) {
  const totalStars = results.reduce((sum, result) => sum + result.stars, 0); const score = results.reduce((sum, result) => sum + result.score, 0); const attempts = results.reduce((sum, result) => sum + result.attempts, 0); const correct = results.reduce((sum, result) => sum + result.correct, 0); const combo = Math.max(...results.map((result) => result.bestCombo), 0); const sentences = [...new Set(results.flatMap((result) => result.sentences || []))];
  return <section className="relative mx-auto max-w-4xl py-6 text-center"><div className="pointer-events-none absolute inset-0 text-4xl opacity-70" aria-hidden="true">🎉　⭐　🎊　⭐　🎉</div><div className="relative"><p className="text-sm font-black uppercase tracking-[.25em] text-yellow-300">LEAD Family Champion</p><h2 className="mt-3 font-heading text-5xl font-black sm:text-7xl">🏆 {name}</h2><p className="mt-3 text-blue-100">Speak English with Confidence</p><div className="mt-7 grid gap-3 sm:grid-cols-5">{stageNames.map((stage, index) => <div key={stage} className="rounded-2xl border border-white/15 bg-white/10 p-3"><p className="text-xs font-black uppercase text-blue-200">{stage}</p><p className="mt-2">{"⭐".repeat(results[index]?.stars || 0)}</p></div>)}</div><div className="mx-auto mt-6 grid max-w-2xl grid-cols-2 gap-3 sm:grid-cols-4"><Stat dark label="Total" value={`${totalStars}/15 ⭐`} /><Stat dark label="Score" value={score.toLocaleString()} /><Stat dark label="Accuracy" value={`${Math.round(correct / Math.max(1, attempts) * 100)}%`} /><Stat dark label="Best combo" value={`x${combo}`} /></div>{sentences.length ? <div className="mx-auto mt-6 max-w-2xl rounded-2xl bg-white/10 p-5 text-left"><p className="text-xs font-black uppercase tracking-widest text-yellow-300">Speaking achievement</p>{sentences.map((sentence) => <p key={sentence} className="mt-2 font-bold">✓ {sentence}</p>)}</div> : null}<div className="mt-7 flex flex-wrap justify-center gap-3"><Button onClick={onReplay}><RotateCcw className="h-4 w-4" />BEAT MY SCORE</Button><Button variant="secondary" onClick={onChange}><UserRound className="h-4 w-4" />CHANGE STUDENT</Button></div></div></section>;
}

function Stat({ label, value, dark = false }: { label: string; value: string; dark?: boolean }) { return <div className={`rounded-xl p-3 ${dark ? "bg-white/10" : "bg-slate-100"}`}><p className={`text-[10px] font-black uppercase ${dark ? "text-blue-200" : "text-slate-500"}`}>{label}</p><p className="mt-1 font-heading text-xl font-black">{value}</p></div>; }
