"use client";

import { useMemo, useState } from "react";
import { Mic, Volume2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { arcadeTone, speak } from "./game-audio";
import { familyMembers, shuffle } from "./game-data";
import type { StageProps } from "./types";

export function FamilyTV({ sound, onComplete, studentName }: StageProps & { studentName: string }) {
  const guests = useMemo(() => shuffle(familyMembers.slice(0, 6)).slice(0, 4), []); const [round, setRound] = useState(0); const [prepared, setPrepared] = useState(false); const [spoken, setSpoken] = useState<string[]>([]); const guest = guests[round]; const prompt = round < 2 ? `Who is ${guest.pronoun}?` : "Introduce this family member.";
  function done() { const sentences = [...spoken, guest.sentence]; setSpoken(sentences); arcadeTone("correct", sound); if (round === guests.length - 1) window.setTimeout(() => onComplete({ stars: 3, score: 1600, correct: 4, attempts: 4, bestCombo: 4, sentences: ["This is my family.", ...sentences] }), 650); else { setRound((value) => value + 1); setPrepared(false); } }
  return <section className="relative min-h-[590px] overflow-hidden rounded-3xl bg-[radial-gradient(circle_at_top,#7c3aed,#312e81_60%,#0f172a)] p-5 text-center"><div className="absolute inset-x-0 top-0 h-52 bg-[linear-gradient(115deg,transparent_30%,rgba(250,204,21,.2)_31%_36%,transparent_37%_62%,rgba(255,255,255,.15)_63%_68%,transparent_69%)]" /><p className="relative text-xs font-black uppercase tracking-[.28em] text-yellow-300">🎤 LEAD Family TV</p><h2 className="relative mt-2 font-heading text-3xl font-black">TODAY&apos;S GUEST: {studentName.toUpperCase()}</h2><div className="relative mx-auto mt-6 max-w-3xl rounded-[2rem] border-4 border-yellow-300 bg-white p-6 text-slate-900 shadow-2xl"><p className="text-sm font-black uppercase text-purple-700">Interview {round + 1}/{guests.length}</p><div className="mt-3 text-8xl">{guest.emoji}</div><h3 className="mt-3 font-heading text-3xl font-black">Host: “{prompt}”</h3>{!prepared ? <div className="mt-6"><p className="font-bold text-slate-600">Think first. When you are ready, reveal your speaking cue.</p><Button onClick={() => setPrepared(true)} className="mt-4">I&apos;M READY</Button></div> : <div className="mt-5 rounded-2xl bg-blue-50 p-5"><p className="text-xs font-black uppercase tracking-widest text-blue-600">🎤 Say it aloud</p><p className="mt-2 font-heading text-2xl font-black">{round < 2 ? guest.sentence : "Introduce the character in your own words."}</p><div className="mt-4 flex flex-wrap justify-center gap-3"><Button variant="secondary" onClick={() => speak(guest.sentence, sound)}><Volume2 className="h-4 w-4" />LISTEN</Button><Button onClick={done}><Mic className="h-4 w-4" />I SAID IT</Button></div><p className="mt-3 text-xs font-semibold text-slate-500">A teacher can listen and give pronunciation feedback.</p></div>}</div><div className="relative mt-5 text-3xl" aria-hidden="true">👏　👏　✨　👏　👏</div></section>;
}
