"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, ArrowRight, ArrowUp, Shield } from "lucide-react";
import { arcadeTone, speak } from "./game-audio";
import { familyMembers, shuffle } from "./game-data";
import type { StageProps } from "./types";

export function FamilyRush({ sound, onComplete }: StageProps) {
  const rounds = useMemo(() => shuffle(familyMembers).slice(0, 7), []); const [round, setRound] = useState(0); const [lane, setLane] = useState(1); const laneRef = useRef(1); const [jumping, setJumping] = useState(false); const [score, setScore] = useState(0); const [correct, setCorrect] = useState(0); const [combo, setCombo] = useState(0); const [best, setBest] = useState(0); const [shield, setShield] = useState(true); const target = rounds[round];
  const options = useMemo(() => target ? shuffle([target, ...shuffle(familyMembers.filter((item) => item.id !== target.id)).slice(0, 2)]) : [], [target]);
  const clue = round < 2 ? target.word : target.sentence;
  const move = useCallback((direction: -1 | 1) => setLane((current) => Math.max(0, Math.min(2, current + direction))), []);
  const jump = useCallback(() => { setJumping(true); window.setTimeout(() => setJumping(false), 550); }, []);
  useEffect(() => { laneRef.current = lane; }, [lane]);
  useEffect(() => { const keydown = (event: KeyboardEvent) => { if (["ArrowLeft", "ArrowRight", "ArrowUp", "a", "d", "w", " "].includes(event.key)) event.preventDefault(); if (event.key === "ArrowLeft" || event.key.toLowerCase() === "a") move(-1); if (event.key === "ArrowRight" || event.key.toLowerCase() === "d") move(1); if (event.key === "ArrowUp" || event.key.toLowerCase() === "w" || event.key === " ") jump(); }; window.addEventListener("keydown", keydown); return () => window.removeEventListener("keydown", keydown); }, [jump, move]);
  useEffect(() => { const timer = window.setTimeout(() => speak(clue, sound), 200); return () => window.clearTimeout(timer); }, [clue, sound]);
  function choose(chosenLane?: number | React.MouseEvent<HTMLButtonElement>) { const resolvedLane = typeof chosenLane === "number" ? chosenLane : laneRef.current; const hit = options[resolvedLane].id === target.id; const attempts = round + 1; let nextCorrect = correct; let nextScore = score; let nextBest = best; if (hit) { const nextCombo = combo + 1; nextCorrect += 1; nextScore += 150 * nextCombo; nextBest = Math.max(best, nextCombo); setCombo(nextCombo); setCorrect(nextCorrect); setScore(nextScore); setBest(nextBest); arcadeTone("correct", sound); } else if (shield) { setShield(false); arcadeTone("wrong", sound); } else { setCombo(0); arcadeTone("wrong", sound); } if (round === rounds.length - 1) { const accuracy = nextCorrect / rounds.length; window.setTimeout(() => onComplete({ stars: accuracy >= .8 ? 3 : accuracy >= .55 ? 2 : 1, score: nextScore + 300, correct: nextCorrect, attempts, bestCombo: nextBest }), 350); } else setRound((value) => value + 1); }
  if (!target) return null;
  return <section className="relative min-h-[590px] overflow-hidden rounded-3xl bg-[linear-gradient(#38bdf8_0_35%,#15803d_35%_48%,#334155_48%)] p-4"><div className="relative z-20 flex items-start justify-between"><div className="rounded-2xl bg-slate-950/85 px-4 py-3"><p className="text-xs font-black uppercase text-yellow-300">Listen and choose a lane</p><p className="mt-1 text-lg font-black">“{clue}”</p></div><div className="flex gap-2"><span className="rounded-full bg-yellow-400 px-3 py-2 text-xs font-black text-slate-950">{score} pts</span>{shield ? <span className="rounded-full bg-blue-500 p-2" title="Wisey Shield"><Shield className="h-4 w-4" /></span> : null}</div></div><div className="absolute inset-x-4 bottom-20 top-28 grid grid-cols-3 gap-2 perspective-[500px]">{options.map((option, index) => <button key={option.id} onClick={() => { setLane(index); window.setTimeout(choose, 100); }} className={`relative overflow-hidden rounded-t-[3rem] border-x-4 border-dashed transition ${lane === index ? "border-yellow-300 bg-white/20" : "border-white/25 bg-slate-900/20"}`}><span className="absolute left-1/2 top-[12%] -translate-x-1/2 animate-[runner-gate_1.15s_linear_infinite] rounded-2xl border-4 border-white bg-white px-4 py-3 text-center text-slate-900 shadow-xl"><span className="block text-5xl">{option.emoji}</span><span className="text-xs font-black">{option.word.toUpperCase()}</span></span>{round > 1 ? <span className="absolute bottom-[20%] left-1/2 -translate-x-1/2 text-4xl">{index === (round + 1) % 3 ? "🧸" : "⭐"}</span> : null}</button>)}</div><div className="absolute bottom-14 left-0 right-0 grid grid-cols-3"><span /><div className="text-center text-6xl transition-all duration-150" style={{ transform: `translateX(${(lane - 1) * 100}%) translateY(${jumping ? -70 : 0}px)` }}>🏃</div><span /></div><div className="absolute inset-x-4 bottom-3 flex justify-center gap-3"><button onClick={() => move(-1)} className="rounded-xl bg-white/15 p-3"><ArrowLeft /></button><button onClick={jump} className="rounded-xl bg-yellow-400 p-3 text-slate-900"><ArrowUp /></button><button onClick={() => move(1)} className="rounded-xl bg-white/15 p-3"><ArrowRight /></button><button onClick={choose} className="rounded-xl bg-emerald-500 px-5 py-3 font-black">RUN THROUGH</button></div><style jsx>{`@keyframes runner-gate{from{transform:translate(-50%,-40%) scale(.6)}to{transform:translate(-50%,220%) scale(1.25)}}`}</style></section>;
}
