"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, ArrowUp } from "lucide-react";
import { arcadeTone, speak } from "./game-audio";
import { familyMembers, shuffle } from "./game-data";
import type { StageProps } from "./types";

type Mission = { clue: string; answer: string; choices: Array<{ word: string; emoji: string }> };

export function FamilyEscape({ sound, onComplete }: StageProps) {
  const missions = useMemo<Mission[]>(() => { const selected = shuffle(familyMembers).slice(0, 6); return selected.map((target, index) => ({ clue: index < 2 ? target.word : index < 4 ? target.sentence : `Recover ${target.word} from the album!`, answer: target.word, choices: shuffle([target, ...shuffle(familyMembers.filter((item) => item.id !== target.id)).slice(0, 2)]).map((item) => ({ word: item.word, emoji: item.emoji })) })); }, []);
  const [mission, setMission] = useState(0); const [lane, setLane] = useState(1); const [jumping, setJumping] = useState(false); const [score, setScore] = useState(0); const [correct, setCorrect] = useState(0); const [combo, setCombo] = useState(0); const [best, setBest] = useState(0); const [hearts, setHearts] = useState(3); const current = missions[mission];
  const move = useCallback((direction: -1 | 1) => setLane((value) => Math.max(0, Math.min(2, value + direction))), []); const jump = useCallback(() => { setJumping(true); window.setTimeout(() => setJumping(false), 500); }, []);
  useEffect(() => { const key = (event: KeyboardEvent) => { if (["ArrowLeft", "ArrowRight", "ArrowUp", "a", "d", "w", " "].includes(event.key)) event.preventDefault(); if (event.key === "ArrowLeft" || event.key.toLowerCase() === "a") move(-1); if (event.key === "ArrowRight" || event.key.toLowerCase() === "d") move(1); if (event.key === "ArrowUp" || event.key.toLowerCase() === "w" || event.key === " ") jump(); }; window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); }, [jump, move]);
  useEffect(() => { if (current) speak(current.clue, sound); }, [current, sound]);
  function collect(chosenLane = lane) { const hit = current.choices[chosenLane].word === current.answer; let nextCorrect = correct; let nextScore = score; let nextBest = best; if (hit) { const nextCombo = combo + 1; nextCorrect += 1; nextScore += 250 * nextCombo; nextBest = Math.max(best, nextCombo); setCorrect(nextCorrect); setCombo(nextCombo); setScore(nextScore); setBest(nextBest); arcadeTone("correct", sound); } else { setHearts((value) => Math.max(1, value - 1)); setCombo(0); arcadeTone("wrong", sound); } if (mission === missions.length - 1) { const accuracy = nextCorrect / missions.length; window.setTimeout(() => onComplete({ stars: accuracy >= .8 ? 3 : accuracy >= .5 ? 2 : 1, score: nextScore + hearts * 300, correct: nextCorrect, attempts: missions.length, bestCombo: nextBest }), 500); } else setMission((value) => value + 1); }
  if (!current) return null;
  return <section className="relative min-h-[590px] overflow-hidden rounded-3xl bg-[linear-gradient(#111827,#312e81_48%,#78350f_49%,#1c1917)] p-4"><div className="absolute inset-0 opacity-25 [background-image:linear-gradient(90deg,transparent_48%,#facc15_49%_51%,transparent_52%)] [background-size:33.33%_100%]" /><div className="relative z-20 flex justify-between"><div className="rounded-2xl border border-yellow-300 bg-slate-950/90 px-4 py-3"><p className="text-xs font-black uppercase text-yellow-300">Album Escape · Phase {mission + 1}/{missions.length}</p><p className="mt-1 text-lg font-black">🔊 “{current.clue}”</p></div><div className="text-right font-black"><p>{"❤️".repeat(hearts)}</p><p className="mt-1 text-yellow-300">{score.toLocaleString()} · x{combo}</p></div></div><div className="absolute inset-x-4 bottom-20 top-28 grid grid-cols-3 gap-3">{current.choices.map((choice, index) => <button key={`${mission}-${choice.word}`} onClick={() => { setLane(index); collect(index); }} className={`focus-ring relative overflow-hidden rounded-t-full border-4 transition ${lane === index ? "border-yellow-300 bg-yellow-300/15" : "border-purple-300/30 bg-black/20"}`}><span className="absolute left-1/2 top-[12%] -translate-x-1/2 animate-[escape-rush_1.05s_linear_infinite] rounded-2xl border-4 border-yellow-200 bg-amber-50 px-4 py-3 text-slate-950 shadow-2xl"><span className="block text-5xl">{choice.emoji}</span><span className="text-xs font-black">{choice.word.toUpperCase()}</span></span><span className="absolute bottom-[18%] left-1/2 -translate-x-1/2 text-3xl">{index === mission % 3 ? "📕" : "⭐"}</span></button>)}</div><div className="absolute bottom-14 left-0 right-0 grid grid-cols-3"><span /><div className="text-center text-6xl transition-all duration-150" style={{ transform: `translateX(${(lane - 1) * 100}%) translateY(${jumping ? -65 : 0}px)` }}>🏃‍♀️</div><span /></div><div className="absolute inset-x-3 bottom-3 flex justify-center gap-2"><button onClick={() => move(-1)} className="rounded-xl bg-white/15 p-3"><ArrowLeft /></button><button onClick={jump} className="rounded-xl bg-yellow-400 p-3 text-slate-900"><ArrowUp /></button><button onClick={() => move(1)} className="rounded-xl bg-white/15 p-3"><ArrowRight /></button><button onClick={() => collect()} className="rounded-xl bg-emerald-500 px-5 py-3 font-black">COLLECT</button></div><style jsx>{`@keyframes escape-rush{from{transform:translate(-50%,-45%) scale(.55)}to{transform:translate(-50%,250%) scale(1.3)}}`}</style></section>;
}
