"use client";

import { useEffect, useMemo, useState } from "react";
import { Volume2 } from "lucide-react";
import { arcadeTone, speak } from "./game-audio";
import { member, sentenceChallenges, shuffle } from "./game-data";
import type { StageProps } from "./types";

const distractors = ["a", "the", "are", "father", "brother", "she", "he"];

export function SentenceFlight({ sound, onComplete }: StageProps) {
  const challenges = useMemo(() => shuffle(sentenceChallenges).slice(0, 4), []); const [round, setRound] = useState(0); const [wordIndex, setWordIndex] = useState(0); const [altitude, setAltitude] = useState(50); const [score, setScore] = useState(0); const [combo, setCombo] = useState(0); const [best, setBest] = useState(0); const [correct, setCorrect] = useState(0); const [attempts, setAttempts] = useState(0); const challenge = challenges[round]; const wanted = challenge.words[wordIndex];
  const gates = useMemo(() => wanted ? shuffle([wanted, ...shuffle(distractors.filter((word) => word.toLowerCase() !== wanted.toLowerCase())).slice(0, 2)]) : [], [wanted]);
  useEffect(() => { const fall = window.setInterval(() => setAltitude((value) => Math.min(82, value + 2)), 140); return () => window.clearInterval(fall); }, []);
  useEffect(() => { const press = (event: KeyboardEvent) => { if (event.key === " ") { event.preventDefault(); setAltitude((value) => Math.max(10, value - 13)); } }; window.addEventListener("keydown", press); return () => window.removeEventListener("keydown", press); }, []);
  function fly(word: string, gateIndex: number) { setAltitude(18 + gateIndex * 30); const nextAttempts = attempts + 1; setAttempts(nextAttempts); if (word.toLowerCase() !== wanted.toLowerCase()) { setCombo(0); arcadeTone("wrong", sound); return; } const nextCorrect = correct + 1; const nextCombo = combo + 1; const nextBest = Math.max(best, nextCombo); const nextScore = score + 120 * nextCombo; setCorrect(nextCorrect); setCombo(nextCombo); setBest(nextBest); setScore(nextScore); arcadeTone("correct", sound); if (wordIndex < challenge.words.length - 1) setWordIndex((value) => value + 1); else { speak(challenge.sentence, sound); if (round === challenges.length - 1) { const accuracy = nextCorrect / nextAttempts; window.setTimeout(() => onComplete({ stars: accuracy >= .85 ? 3 : accuracy >= .6 ? 2 : 1, score: nextScore + 500, correct: nextCorrect, attempts: nextAttempts, bestCombo: nextBest, sentences: challenges.map((item) => item.sentence) }), 600); } else { setRound((value) => value + 1); setWordIndex(0); } } }
  if (!challenge) return null;
  return <section onPointerDown={(event) => { if ((event.target as HTMLElement).closest("button")) return; setAltitude((value) => Math.max(10, value - 13)); }} className="relative min-h-[590px] select-none overflow-hidden rounded-3xl bg-[linear-gradient(#38bdf8,#dbeafe_58%,#86efac_59%)] p-4 text-slate-900"><div className="relative z-20 rounded-2xl bg-white/90 p-4 shadow-lg"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-widest text-blue-600">Build the sentence · {round + 1}/{challenges.length}</p><h2 className="font-heading text-2xl font-black">{round < 2 ? challenge.sentence.replace(/\w+\.$/, "_____.") : `${member(challenge.member).emoji} Introduce this family member`}</h2></div><button onClick={() => speak(challenge.sentence, sound)} aria-label="Listen to sentence" className="rounded-full bg-blue-100 p-3 text-blue-700"><Volume2 /></button></div><p className="mt-2 font-bold text-emerald-700">Collected: {challenge.words.slice(0, wordIndex).join(" ") || "Fly through the first word"}</p></div><div className="absolute left-[12%] text-6xl transition-all duration-150" style={{ top: `${altitude}%`, transform: "translateY(-50%) rotate(-8deg)" }}>🦉✈️</div><div className="absolute bottom-8 right-[8%] top-32 grid w-[48%] grid-rows-3 gap-8">{gates.map((word, index) => <button key={`${word}-${wordIndex}`} onClick={() => fly(word, index)} className="focus-ring animate-[gate-slide_2.2s_linear_infinite] rounded-2xl border-4 border-white bg-[#0f172a]/90 px-4 py-3 text-xl font-black uppercase text-white shadow-2xl hover:bg-blue-700">{word}</button>)}</div><div className="absolute bottom-3 left-4 rounded-xl bg-slate-950/80 px-4 py-2 text-xs font-bold text-white">SPACE / TAP SKY to rise · Choose words in order · Combo x{combo}</div><style jsx>{`@keyframes gate-slide{from{translate:35px 0}to{translate:-25px 0}}`}</style></section>;
}
