"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { arcadeSound, speakArcade } from "../lead-arcade/audio";
import type { ArcadeStageProps } from "../lead-arcade/types";
import { requestFor, restaurantItems, shuffle, type RestaurantItem } from "./game-data";

type RushOrder = { id: number; table: number; items: RestaurantItem[]; served: string[]; phrase: string; hidden: boolean };

export function DinnerRush({ sound, onComplete }: ArcadeStageProps) {
  const [countdown, setCountdown] = useState(3); const [time, setTime] = useState(55); const [orders, setOrders] = useState<RushOrder[]>([]); const [carry, setCarry] = useState<RestaurantItem | null>(null); const [score, setScore] = useState(0); const [combo, setCombo] = useState(0); const [best, setBest] = useState(0); const [correct, setCorrect] = useState(0); const [attempts, setAttempts] = useState(0); const [boss, setBoss] = useState(false); const [bossItems, setBossItems] = useState<string[]>([]); const kitchen = useMemo(() => shuffle(restaurantItems), []); const timeRef = useRef(time);
  useEffect(() => { timeRef.current = time; }, [time]);
  useEffect(() => { if (countdown <= 0) return; const timer = window.setTimeout(() => setCountdown((value) => value - 1), 850); return () => window.clearTimeout(timer); }, [countdown]);
  useEffect(() => { if (countdown > 0 || boss) return; const timer = window.setInterval(() => setTime((value) => Math.max(0, value - 1)), 1000); return () => window.clearInterval(timer); }, [countdown, boss]);
  useEffect(() => {
    if (countdown > 0 || boss) return;
    const spawn = window.setInterval(() => setOrders((current) => { const remaining = timeRef.current; if (current.length >= (remaining < 20 ? 4 : 3)) return current; const pool = shuffle(restaurantItems.slice(0, remaining < 30 ? 15 : 8)); const items = remaining < 38 && Math.random() > .45 ? pool.slice(0, 2) : pool.slice(0, 1); const id = Date.now() + Math.random(); const phrase = `${requestFor(items[0])}${items[1] ? ` Anything else? Yes, please. ${items[1].article} ${items[1].name}.` : ""}`; window.setTimeout(() => speakArcade(phrase, sound), 100); return [...current, { id, table: 1 + Math.floor(Math.random() * 8), items, served: [], phrase, hidden: remaining < 28 }]; }), 2200);
    return () => window.clearInterval(spawn);
  }, [countdown, boss, sound]);
  useEffect(() => { if (time > 0 || boss) return; setBoss(true); setOrders([]); speakArcade("Hello! I'd like a pizza, please. Can I have some fries too? Yes, some juice, please.", sound); }, [time, boss, sound]);
  function serve(order: RushOrder) { if (!carry) return; setAttempts((value) => value + 1); const needed = order.items.find((item) => !order.served.includes(item.id)); if (needed?.id === carry.id) { const completed = [...order.served, carry.id]; const nextCombo = combo + 1; setCombo(nextCombo); setBest((value) => Math.max(value, nextCombo)); setCorrect((value) => value + 1); setScore((value) => value + 200 + nextCombo * 60); setOrders((current) => completed.length === order.items.length ? current.filter((item) => item.id !== order.id) : current.map((item) => item.id === order.id ? { ...item, served: completed } : item)); arcadeSound("correct", sound); } else { setCombo(0); arcadeSound("wrong", sound); } setCarry(null); }
  function serveBoss(item: RestaurantItem) { const target = ["pizza", "fries", "juice"][bossItems.length]; setAttempts((value) => value + 1); if (item.id === target) { const next = [...bossItems, item.id]; setBossItems(next); setCorrect((value) => value + 1); setScore((value) => value + 500); arcadeSound("correct", sound); if (next.length === 3) window.setTimeout(() => onComplete({ stars: correct >= 12 ? 3 : correct >= 7 ? 2 : 1, score: score + 500, correct: correct + 1, attempts: attempts + 1, bestCombo: best, practiced: ["Can I have a burger, please?", "I'd like a pizza, please.", "Anything else?", "No, thank you."] }), 900); } else arcadeSound("wrong", sound); }
  if (countdown > 0) return <section className="grid min-h-[620px] place-items-center text-center"><div><p className="text-xl font-black text-yellow-300">🔥 FRIDAY NIGHT DINNER RUSH!</p><h2 className="mt-6 font-heading text-9xl font-black animate-ping">{countdown}</h2><p className="mt-8 text-2xl font-black">Wisey: “We need you!”</p></div></section>;
  if (boss) return <section className="grid min-h-[620px] place-items-center text-center"><div className="w-full max-w-4xl rounded-[2rem] border-4 border-yellow-300 bg-white p-7 text-slate-900"><p className="text-sm font-black uppercase tracking-widest text-rose-600">Final customer · Boss order</p><div className="mt-3 text-8xl">🕴️</div><p className="mt-4 font-heading text-2xl font-black">“I&apos;d like a pizza, fries, and some juice, please.”</p><button onClick={() => speakArcade("I'd like a pizza, please. Can I have some fries too? Yes, some juice, please.", sound)} className="mt-3 rounded-lg bg-blue-100 px-4 py-2 font-black text-blue-700">🔊 Replay order</button><div className="mt-6 flex justify-center gap-4">{restaurantItems.filter((item) => ["pizza", "fries", "juice", "burger", "water"].includes(item.id)).map((item) => <button key={item.id} onClick={() => serveBoss(item)} className="rounded-xl bg-amber-50 p-4 shadow"><span className="block text-5xl">{item.emoji}</span><span className="font-black uppercase">{item.name}</span></button>)}</div><p className="mt-5 text-3xl">{bossItems.map((id) => restaurantItems.find((item) => item.id === id)?.emoji).join(" ")} {bossItems.length < 3 ? "□" : "✅"}</p></div></section>;
  return <section className="mx-auto max-w-6xl"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase text-yellow-300">Friday night dinner rush</p><h2 className="font-heading text-3xl font-black">Listen · Collect · Serve</h2></div><div className={`rounded-xl px-4 py-2 font-heading text-2xl font-black ${time < 15 ? "animate-pulse bg-rose-600" : "bg-white/10"}`}>⏱ {time}s</div><div className="font-black">{score} · 🔥 x{combo}</div></div><div className="mt-4 grid gap-4 lg:grid-cols-[1fr_310px]"><div className="grid auto-rows-fr gap-3 sm:grid-cols-2">{orders.map((order) => <div key={order.id} className="min-h-44 rounded-[2rem] border-4 border-amber-200 bg-white p-4 text-slate-900"><button type="button" onClick={() => serve(order)} className="w-full"><div className="flex items-center justify-between"><span className="text-5xl">{["👧", "👦", "👩", "👨"][order.table % 4]}</span><span className="rounded-full bg-blue-100 px-3 py-1 text-xs font-black text-blue-700">TABLE {order.table}</span></div>{order.hidden ? <p className="mt-3 font-black text-slate-500">🔊 Listening order</p> : <p className="mt-3 font-black">{order.items.map((item) => `${item.emoji} ${item.name}`).join(" + ")}</p>}<div className="mt-3">{order.items.map((item) => <span key={item.id} className="mx-1 text-2xl">{order.served.includes(item.id) ? "✅" : "□"}</span>)}</div></button><button type="button" onClick={() => { speakArcade(order.phrase, sound); setScore((value) => Math.max(0, value - 25)); }} className="mt-3 w-full text-xs font-black text-blue-700">🔊 Replay (-25)</button></div>)}{!orders.length ? <div className="grid min-h-44 place-items-center rounded-[2rem] border border-white/20 bg-white/5 p-5 text-center font-black">Kitchen ready... next customer arriving!</div> : null}</div><aside className="rounded-[2rem] bg-slate-100 p-4 text-slate-900"><p className="text-xs font-black uppercase tracking-widest text-blue-700">Rush kitchen</p><div className="mt-3 grid grid-cols-3 gap-2">{kitchen.map((item) => <button key={item.id} onClick={() => setCarry(item)} className={`rounded-xl p-2 ${carry?.id === item.id ? "bg-yellow-300 ring-4 ring-blue-500" : "bg-white"}`}><span className="block text-3xl">{item.emoji}</span><span className="text-[9px] font-black uppercase">{item.name}</span></button>)}</div><div className="mt-4 rounded-xl bg-slate-900 p-4 text-center text-white"><p className="text-xs font-black uppercase text-yellow-300">Carrying</p><p className="mt-2 text-5xl">{carry?.emoji || "🍽️"}</p><p className="mt-1 text-xs font-bold">Choose the correct table</p></div></aside></div></section>;
}
