"use client";

import { Maximize2, Minimize2, UserRound, Volume2, VolumeX } from "lucide-react";
import { Button } from "@/components/ui/button";
import { careerRanks, restaurantStages } from "./game-data";
import type { ArcadeStageResult } from "../lead-arcade/types";

export function RestaurantShell({ name, stage, stars, sound, fullscreen, onSound, onFullscreen, onChangeStudent, children }: { name: string; stage: number; stars: number; sound: boolean; fullscreen: boolean; onSound: () => void; onFullscreen: () => void; onChangeStudent: () => void; children: React.ReactNode }) {
  return <div id="restaurant-rush-shell" className="relative overflow-hidden rounded-[2rem] border border-amber-200 bg-[#07142e] text-white shadow-2xl fullscreen:rounded-none">
    <header className="relative z-40 flex flex-wrap items-center justify-between gap-3 border-b border-white/10 bg-[#0f172a]/95 px-4 py-3 sm:px-6"><div><p className="text-xs font-black uppercase tracking-[.2em] text-yellow-300">LEAD · Restaurant Rush</p><p className="text-sm font-bold text-blue-100">{name} · {stage < 5 ? careerRanks[stage] : careerRanks[4]}</p></div><div className="flex items-center gap-2"><span className="rounded-full bg-yellow-400 px-3 py-1.5 text-sm font-black text-slate-950">⭐ {stars}/15</span><IconButton label={sound ? "Mute sound" : "Turn sound on"} onClick={onSound}>{sound ? <Volume2 /> : <VolumeX />}</IconButton><IconButton label={fullscreen ? "Exit fullscreen" : "Enter fullscreen"} onClick={onFullscreen}>{fullscreen ? <Minimize2 /> : <Maximize2 />}</IconButton><IconButton label="Change student" onClick={onChangeStudent}><UserRound /></IconButton></div></header>
    <div className="relative z-30 grid grid-cols-5 border-b border-white/10 bg-white/5">{restaurantStages.map((title, index) => <div key={title} className={`px-1 py-2 text-center text-[10px] font-black uppercase sm:text-xs ${index <= stage ? "text-yellow-300" : "text-slate-500"}`}><span className={`mx-auto mb-1 grid h-6 w-6 place-items-center rounded-full ${index < stage ? "bg-emerald-500" : index === stage ? "bg-yellow-400 text-slate-950" : "bg-slate-700"}`}>{index < stage ? "✓" : index + 1}</span><span className="hidden sm:inline">{title}</span></div>)}</div>
    <main className="relative min-h-[680px] overflow-hidden p-4 sm:p-6">{children}</main>
  </div>;
}

function IconButton({ label, onClick, children }: { label: string; onClick: () => void; children: React.ReactNode }) { return <button type="button" aria-label={label} onClick={onClick} className="focus-ring grid h-9 w-9 place-items-center rounded-lg bg-white/10 hover:bg-white/20 [&_svg]:h-4 [&_svg]:w-4">{children}</button>; }

export function StageIntro({ stage, emoji, purpose, controls, onStart }: { stage: number; emoji: string; purpose: string; controls: string; onStart: () => void }) { return <section className="grid min-h-[620px] place-items-center text-center"><div className="max-w-3xl"><div className="text-8xl animate-bounce">{emoji}</div><p className="mt-5 text-sm font-black uppercase tracking-[.28em] text-yellow-300">Stage {stage + 1} · {careerRanks[stage]}</p><h2 className="mt-3 font-heading text-5xl font-black sm:text-7xl">{restaurantStages[stage]}</h2><p className="mx-auto mt-4 max-w-2xl text-lg font-bold leading-8 text-blue-100">{purpose}</p><div className="mx-auto mt-6 max-w-xl rounded-2xl border border-white/15 bg-white/10 px-5 py-4 text-sm font-bold">Controls: {controls}</div><Button onClick={onStart} className="mt-7 h-14 bg-yellow-400 px-10 font-black text-slate-950 hover:bg-yellow-300">START SHIFT</Button></div></section>; }

export function StageComplete({ result, stage, onContinue }: { result: ArcadeStageResult; stage: number; onContinue: () => void }) {
  const accuracy = Math.round(result.correct / Math.max(1, result.attempts) * 100);
  return <section className="absolute inset-0 z-50 grid place-items-center bg-[#07142e]/95 p-5 text-center"><div className="w-full max-w-lg rounded-[2rem] border-4 border-yellow-300 bg-white p-7 text-slate-900 shadow-2xl"><p className="text-5xl">{Array.from({ length: 3 }, (_, index) => <span key={index} className={index < result.stars ? "" : "grayscale opacity-25"}>⭐</span>)}</p><p className="mt-4 text-sm font-black uppercase tracking-widest text-blue-600">Shift complete!</p><h2 className="mt-2 font-heading text-4xl font-black">{restaurantStages[stage]}</h2><div className="mt-5 grid grid-cols-3 gap-3"><Stat label="Score" value={result.score.toLocaleString()} /><Stat label="Accuracy" value={`${accuracy}%`} /><Stat label="Combo" value={`x${result.bestCombo}`} /></div><p className="mt-6 font-black text-emerald-700">🔓 {stage < 4 ? `${restaurantStages[stage + 1].toUpperCase()} UNLOCKED` : "RESTAURANT STAR EARNED"}</p><Button onClick={onContinue} className="mt-5 w-full">CONTINUE</Button></div></section>;
}

export function Results({ name, results, onReplay, onChange }: { name: string; results: ArcadeStageResult[]; onReplay: () => void; onChange: () => void }) {
  const stars = results.reduce((sum, result) => sum + result.stars, 0); const score = results.reduce((sum, result) => sum + result.score, 0); const correct = results.reduce((sum, result) => sum + result.correct, 0); const attempts = results.reduce((sum, result) => sum + result.attempts, 0); const combo = Math.max(0, ...results.map((result) => result.bestCombo)); const practiced = [...new Set(results.flatMap((result) => result.practiced || []))];
  return <section className="mx-auto max-w-5xl py-4 text-center"><div className="text-5xl">🎉 🍔 ⭐ 🍕 🏆</div><p className="mt-4 text-sm font-black uppercase tracking-[.25em] text-yellow-300">Restaurant Star</p><h2 className="mt-2 font-heading text-6xl font-black">🏆 {name}</h2><div className="mt-7 grid gap-3 sm:grid-cols-5">{restaurantStages.map((title, index) => <div key={title} className="rounded-2xl border border-white/15 bg-white/10 p-3"><p className="text-xs font-black uppercase text-blue-200">{title}</p><p className="mt-2">{"⭐".repeat(results[index]?.stars || 0)}</p></div>)}</div><div className="mx-auto mt-6 grid max-w-3xl grid-cols-2 gap-3 sm:grid-cols-4"><Stat dark label="Total" value={`${stars}/15 ⭐`} /><Stat dark label="Score" value={score.toLocaleString()} /><Stat dark label="Accuracy" value={`${Math.round(correct / Math.max(1, attempts) * 100)}%`} /><Stat dark label="Best combo" value={`x${combo}`} /></div><div className="mx-auto mt-6 max-w-2xl rounded-2xl bg-white/10 p-5 text-left"><p className="text-xs font-black uppercase tracking-widest text-yellow-300">Speaking practiced</p>{practiced.slice(0, 6).map((line) => <p key={line} className="mt-2 font-bold">✓ {line}</p>)}</div><div className="mt-7 flex flex-wrap justify-center gap-3"><Button onClick={onReplay}>BEAT MY SCORE</Button><Button variant="secondary" onClick={onChange}>CHANGE STUDENT</Button></div></section>;
}

function Stat({ label, value, dark = false }: { label: string; value: string; dark?: boolean }) { return <div className={`rounded-xl p-3 ${dark ? "bg-white/10" : "bg-slate-100"}`}><p className={`text-[10px] font-black uppercase ${dark ? "text-blue-200" : "text-slate-500"}`}>{label}</p><p className="mt-1 font-heading text-xl font-black">{value}</p></div>; }
