"use client";

import { forwardRef, useCallback, useEffect, useImperativeHandle, useRef, useState } from "react";
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUp, Check, Medal, Mic, Pause, Play, RotateCcw, Star, Trophy, UserRound, Volume2, VolumeX } from "lucide-react";
import { Button } from "@/components/ui/button";

type ActivityId = "football" | "basketball" | "badminton" | "running" | "playground" | "cycling";
type Screen = "start" | "park" | ActivityId | "championship" | "interview" | "results";
type Stats = { score: number; stars: number; goals: number; baskets: number; bestRally: number; raceTime: number; cyclingTime: number; championship: number };
type GameCanvasHandle = { direction: (key: string, down: boolean) => void; action: (down?: boolean) => void };

const activityData: Record<ActivityId, { name: string; sentence: string; color: string; medal: string }> = {
  football: { name: "Football", sentence: "I play football in the playground.", color: "#16a34a", medal: "Football Medal" },
  basketball: { name: "Basketball", sentence: "I play basketball.", color: "#ea580c", medal: "Basketball Medal" },
  badminton: { name: "Badminton", sentence: "I play badminton.", color: "#7c3aed", medal: "Badminton Medal" },
  running: { name: "Running", sentence: "I can run fast!", color: "#dc2626", medal: "Running Medal" },
  playground: { name: "Playground", sentence: "I like playing with my friends.", color: "#0891b2", medal: "Playground Medal" },
  cycling: { name: "Cycling", sentence: "I can ride a bike.", color: "#2563eb", medal: "Cycling Medal" }
};
const activities = Object.keys(activityData) as ActivityId[];
const initialStats: Stats = { score: 0, stars: 0, goals: 0, baskets: 0, bestRally: 0, raceTime: 0, cyclingTime: 0, championship: 0 };

function say(text: string, muted = false) { if (muted || typeof window === "undefined" || !("speechSynthesis" in window)) return; window.speechSynthesis.cancel(); const utterance = new SpeechSynthesisUtterance(text); utterance.rate = .85; utterance.lang = "en-US"; window.speechSynthesis.speak(utterance); }
function tone(type: "score" | "medal" | "kick", muted: boolean) { if (muted || typeof window === "undefined") return; const AudioContextClass = window.AudioContext || (window as typeof window & { webkitAudioContext?: typeof AudioContext }).webkitAudioContext; if (!AudioContextClass) return; const ctx = new AudioContextClass(); const osc = ctx.createOscillator(); const gain = ctx.createGain(); osc.frequency.value = type === "medal" ? 740 : type === "score" ? 520 : 180; gain.gain.setValueAtTime(.08, ctx.currentTime); gain.gain.exponentialRampToValueAtTime(.001, ctx.currentTime + .18); osc.connect(gain).connect(ctx.destination); osc.start(); osc.stop(ctx.currentTime + .2); }

export function PlaygroundChampionsGame() {
  const [screen, setScreen] = useState<Screen>("start"); const [name, setName] = useState(""); const [medals, setMedals] = useState<ActivityId[]>([]); const [stats, setStats] = useState(initialStats); const [muted, setMuted] = useState(false); const [message, setMessage] = useState("Let's explore! Walk to an activity zone and press SPACE."); const [paused, setPaused] = useState(false); const [favorite, setFavorite] = useState<ActivityId>("football"); const [reason, setReason] = useState("it is fun"); const [spoken, setSpoken] = useState(false); const canvasRef = useRef<GameCanvasHandle>(null);
  const arenaUnlocked = medals.length >= 4;
  function enterActivity(id: ActivityId) { setScreen(id); setMessage(`Welcome to ${activityData[id].name}! ${controlHint(id)}`); say(activityData[id].name, muted); }
  function complete(id: ActivityId, reward: Partial<Stats>) { const first = !medals.includes(id); setMedals((v) => first ? [...v, id] : v); setStats((v) => ({ ...v, ...reward, score: v.score + (first ? 600 : 250) + (reward.score || 0), stars: v.stars + 5 })); tone("medal", muted); setMessage(`${activityData[id].medal} earned! ${activityData[id].sentence}`); say(activityData[id].sentence, muted); setScreen("park"); }
  function reset(keepName: boolean) { setName(keepName ? name : ""); setMedals([]); setStats(initialStats); setFavorite("football"); setReason("it is fun"); setSpoken(false); setScreen(keepName ? "park" : "start"); }
  useEffect(() => { function down(e: KeyboardEvent) { if (["ArrowUp","ArrowDown","ArrowLeft","ArrowRight","w","a","s","d","W","A","S","D"," ","Escape"].includes(e.key)) e.preventDefault(); if (e.key === "Escape") setPaused((v) => !v); else if (e.key === " ") canvasRef.current?.action(true); else canvasRef.current?.direction(e.key.toLowerCase(), true); } function up(e: KeyboardEvent) { if (e.key === " ") canvasRef.current?.action(false); else canvasRef.current?.direction(e.key.toLowerCase(), false); } window.addEventListener("keydown", down); window.addEventListener("keyup", up); return () => { window.removeEventListener("keydown", down); window.removeEventListener("keyup", up); }; }, []);
  if (screen === "start") return <Start onStart={(student) => { setName(student); setScreen("park"); }} />;
  if (screen === "interview") return <Shell name={name} medals={medals} stats={stats} muted={muted} setMuted={setMuted}><Interview name={name} played={medals} favorite={favorite} setFavorite={setFavorite} reason={reason} setReason={setReason} spoken={spoken} setSpoken={setSpoken} muted={muted} onComplete={() => setScreen("results")}/></Shell>;
  if (screen === "results") return <Shell name={name} medals={medals} stats={stats} muted={muted} setMuted={setMuted}><Results name={name} medals={medals} stats={stats} favorite={favorite} onReplay={() => reset(true)} onExplore={() => setScreen("park")} onChange={() => reset(false)}/></Shell>;
  return <Shell name={name} medals={medals} stats={stats} muted={muted} setMuted={setMuted}><div className="grid gap-4 xl:grid-cols-[1fr_270px]"><div><Wisey>{message}</Wisey><div className="relative mt-4 overflow-hidden rounded-3xl border-4 border-lead-navy bg-slate-900"><SportsCanvas ref={canvasRef} mode={screen} paused={paused} medals={medals} muted={muted} onActivity={enterActivity} onMessage={setMessage} onScore={(points) => setStats((v) => ({ ...v, score: v.score + points }))} onComplete={complete} onChampionship={() => { if (arenaUnlocked) setScreen("championship"); else setMessage(`Earn ${4 - medals.length} more medal${4 - medals.length === 1 ? "" : "s"} to unlock the Championship Arena.`); }} onInterview={() => setScreen("interview")}/>{paused ? <div className="absolute inset-0 grid place-items-center bg-lead-navy/80"><div className="text-center text-white"><Pause className="mx-auto h-14 w-14"/><p className="mt-3 font-heading text-4xl font-black">Paused</p><Button className="mt-4" onClick={() => setPaused(false)}><Play className="h-4 w-4"/>Resume</Button></div></div> : null}</div></div><aside className="space-y-3"><Card title={screen === "park" ? "Explore the Park" : screen === "championship" ? "Championship" : activityData[screen].name}><p className="text-sm font-bold leading-6 text-lead-navy">{screen === "park" ? "Walk to a glowing activity sign. SPACE starts the challenge." : screen === "championship" ? "Win five skill trials. Watch the target, time each action, and react quickly." : controlHint(screen)}</p></Card><Card title="Champion Medals"><div className="grid gap-2">{activities.map((id) => <div key={id} className={`flex items-center justify-between rounded-lg px-3 py-2 text-xs font-black ${medals.includes(id) ? "bg-emerald-50 text-emerald-700" : "bg-slate-50 text-slate-500"}`}><span>{activityData[id].name}</span>{medals.includes(id) ? <Check className="h-4 w-4"/> : <span>—</span>}</div>)}</div><div className={`mt-3 rounded-xl p-3 text-xs font-black ${arenaUnlocked ? "bg-yellow-100 text-amber-800" : "bg-slate-100 text-slate-600"}`}>{arenaUnlocked ? "Championship Arena unlocked!" : `${medals.length}/4 medals to unlock arena`}</div></Card><Card title="Controls"><p className="text-xs font-semibold leading-6 text-lead-gray">WASD / Arrows · Move<br/>SPACE · Action / Jump / Shoot<br/>ESC · Pause</p><TouchControls refHandle={canvasRef}/></Card></aside></div></Shell>;
}

function Shell({ name, medals, stats, muted, setMuted, children }: { name: string; medals: ActivityId[]; stats: Stats; muted: boolean; setMuted: (v: boolean) => void; children: React.ReactNode }) { return <div className="overflow-hidden rounded-[28px] border border-blue-100 bg-white shadow-soft"><header className="bg-lead-navy px-5 py-4 text-white"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-yellow-300">LEAD · Sports Park</p><p className="font-heading text-xl font-black">Playground Champions</p></div><div className="flex items-center gap-2 text-xs font-black"><span className="rounded-lg bg-white/10 px-3 py-2">{name}</span><span className="rounded-lg bg-blue-600 px-3 py-2">{stats.score} pts</span><span className="flex items-center gap-1 rounded-lg bg-yellow-400 px-3 py-2 text-lead-navy"><Medal className="h-4 w-4"/>{medals.length}</span><button aria-label={muted ? "Turn sound on" : "Mute sound"} className="focus-ring rounded-lg bg-white/10 p-2" onClick={() => setMuted(!muted)}>{muted ? <VolumeX className="h-4 w-4"/> : <Volume2 className="h-4 w-4"/>}</button></div></div></header><div className="min-h-[640px] p-4 sm:p-6">{children}</div></div>; }

const SportsCanvas = forwardRef<GameCanvasHandle, { mode: Exclude<Screen,"start"|"interview"|"results">; paused: boolean; medals: ActivityId[]; muted: boolean; onActivity: (id: ActivityId) => void; onMessage: (text: string) => void; onScore: (points: number) => void; onComplete: (id: ActivityId, stats: Partial<Stats>) => void; onChampionship: () => void; onInterview: () => void }>(function SportsCanvas(props, ref) {
  const canvasRef = useRef<HTMLCanvasElement>(null); const keys = useRef(new Set<string>()); const action = useRef(false); const state = useRef<Record<string, number>>({ px: 480, py: 475, vx: 0, vy: 0, bx: 510, by: 430, bvx: 0, bvy: 0, round: 1, scored: 0, power: 0, charging: 0, rally: 0, elapsed: 0, jump: 0, distance: 0, checkpoint: 0, playground: 0, pgProgress: 0, pgLast: 0, pgCooldown: 0, championRound: 0, championProgress: 0, championLast: 0, championCooldown: 0, championMisses: 0 }); const nearby = useRef<ActivityId | "arena" | "interview" | null>(null); const modeRef = useRef(props.mode); modeRef.current = props.mode;
  function resetMode(mode: string) { const s = state.current; s.px = mode === "running" ? 100 : 480; s.py = mode === "running" ? 430 : 475; s.vx = s.vy = 0; s.bx = mode === "football" ? 510 : 480; s.by = mode === "football" ? 410 : 420; s.bvx = s.bvy = 0; s.round = 1; s.scored = 0; s.power = 0; s.charging = 0; s.rally = 0; s.elapsed = 0; s.jump = 0; s.distance = 0; s.checkpoint = 0; s.playground = 0; s.pgProgress = 0; s.pgLast = 0; s.pgCooldown = 0; s.championRound = 0; s.championProgress = 0; s.championLast = 0; s.championCooldown = 0; s.championMisses = 0; }
  useEffect(() => resetMode(props.mode), [props.mode]);
  useImperativeHandle(ref, () => ({ direction(key, down) { if (down) keys.current.add(key); else keys.current.delete(key); }, action(down = true) { action.current = down; if (!down && modeRef.current === "basketball") shootBasket(); } }));
  const shootBasket = useCallback(() => { const s = state.current; if (!s.charging || s.bvy) return; s.bx = s.px; s.by = 420; s.bvx = (480 - s.px) * .7; s.bvy = -(350 + s.power * 4); s.charging = 0; tone("kick", props.muted); }, [props.muted]);
  // Canvas simulation functions intentionally read the latest refs and props inside the animation loop.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { const canvas = canvasRef.current; const ctx = canvas?.getContext("2d"); if (!canvas || !ctx) return; let frame = 0, last = performance.now(); function loop(now: number) { const dt = Math.min(.035, (now-last)/1000); last = now; if (!props.paused) update(dt); draw(ctx!); frame = requestAnimationFrame(loop); } frame = requestAnimationFrame(loop); return () => cancelAnimationFrame(frame); }, [props.mode, props.paused]);
  function movement(dt: number, speed = 220) { const s = state.current; let dx=0,dy=0; if(keys.current.has("arrowleft")||keys.current.has("a"))dx--;if(keys.current.has("arrowright")||keys.current.has("d"))dx++;if(keys.current.has("arrowup")||keys.current.has("w"))dy--;if(keys.current.has("arrowdown")||keys.current.has("s"))dy++;if(dx&&dy){dx*=.707;dy*=.707;}s.px=Math.max(28,Math.min(932,s.px+dx*speed*dt));s.py=Math.max(60,Math.min(555,s.py+dy*speed*dt)); }
  function update(dt: number) { const s=state.current; s.elapsed+=dt; if(props.mode==="park"){movement(dt); const zones:{id:ActivityId|"arena"|"interview";x:number;y:number}[]=[{id:"football",x:150,y:150},{id:"basketball",x:420,y:145},{id:"badminton",x:700,y:150},{id:"running",x:145,y:425},{id:"playground",x:440,y:430},{id:"cycling",x:720,y:425},{id:"arena",x:865,y:285},{id:"interview",x:70,y:285}];const close=zones.map(z=>({...z,d:Math.hypot(s.px-z.x,s.py-z.y)})).sort((a,b)=>a.d-b.d)[0];nearby.current=close.d<72?close.id:null;if(action.current&&nearby.current){action.current=false;if(nearby.current==="arena")props.onChampionship();else if(nearby.current==="interview")props.onInterview();else props.onActivity(nearby.current);}}
    else if(props.mode==="football"){movement(dt,185);s.bx+=s.bvx*dt;s.by+=s.bvy*dt;s.bvx*=Math.pow(.45,dt);s.bvy*=Math.pow(.45,dt);if(Math.hypot(s.px-s.bx,s.py-s.by)<48&&action.current){action.current=false;const aim=(s.px-480)*-.55;s.bvx=aim;s.bvy=-410-toneNumber();tone("kick",props.muted);}if(s.by<78&&s.bx>365&&s.bx<595){s.scored++;props.onScore(100*s.round);tone("score",props.muted);s.round++;s.bx=510;s.by=410;s.bvx=s.bvy=0;if(s.scored>=3)props.onComplete("football",{goals:3});}if(s.by<20||s.bx<0||s.bx>960){s.bx=510;s.by=410;s.bvx=s.bvy=0;}}
    else if(props.mode==="basketball"){movement(dt,155);if(action.current&&!s.bvy){s.charging=1;s.power=(s.power+70*dt)%100;}if(s.bvy||s.bvx){s.bvy+=610*dt;s.bx+=s.bvx*dt;s.by+=s.bvy*dt;if(s.bvy>0&&s.by>155&&s.by<190&&Math.abs(s.bx-480)<34){s.scored++;props.onScore(150*s.round);tone("score",props.muted);s.round++;s.bvx=s.bvy=0;s.bx=s.px;s.by=420;s.power=0;if(s.scored>=3)props.onComplete("basketball",{baskets:3});}else if(s.by>570){s.bvx=s.bvy=0;s.bx=s.px;s.by=420;s.power=0;}}}
    else if(props.mode==="badminton"){let dx=0;if(keys.current.has("arrowleft")||keys.current.has("a"))dx--;if(keys.current.has("arrowright")||keys.current.has("d"))dx++;s.px=Math.max(90,Math.min(870,s.px+dx*260*dt));s.bx+=s.bvx*dt;s.by+=s.bvy*dt;s.bvy+=170*dt;if(s.by<90){s.by=90;s.bvy=Math.abs(s.bvy);}if(s.by>505&&Math.abs(s.bx-s.px)<90&&action.current){action.current=false;s.bvy=-315;s.bvx=(480-s.px)*.45;s.rally++;tone("kick",props.muted);if(s.rally>=8)props.onComplete("badminton",{bestRally:s.rally});}if(s.by>590){s.rally=0;s.bx=480;s.by=180;s.bvx=90;s.bvy=40;}}
    else if(props.mode==="running"){const fast=keys.current.has("arrowright")||keys.current.has("d");s.distance+=(fast?235:125)*dt;if(action.current&&s.jump===0){action.current=false;s.jump=1;s.vy=-390;tone("kick",props.muted);}if(s.jump){s.vy+=880*dt;s.py+=s.vy*dt;if(s.py>=430){s.py=430;s.vy=0;s.jump=0;}}if(s.distance>=1500)props.onComplete("running",{raceTime:Math.round(s.elapsed)});}
    else if(props.mode==="playground"){movement(dt,190);s.pgCooldown=Math.max(0,s.pgCooldown-dt);const stations=[[150,180],[330,180],[510,180],[690,180],[810,390]];const target=stations[s.playground];const close=target&&Math.hypot(s.px-target[0],s.py-target[1])<78;const finish=()=>{const labels=["Swing mastered!","Slide mastered!","Seesaw mastered!","Climbing mastered!","Skipping mastered!"];props.onScore(250);tone("score",props.muted);props.onMessage(`${labels[s.playground]} ${s.playground<4?"Move to the next station for a new challenge.":"You completed every playground skill!"}`);s.playground++;s.pgProgress=0;s.pgLast=0;s.pgCooldown=.35;if(s.playground>=5)props.onComplete("playground",{});};if(close&&s.playground===0&&action.current){action.current=false;const power=(Math.sin(s.elapsed*3.1)+1)/2;if(power>.42&&power<.62){s.pgProgress++;props.onMessage(`Strong swing pump! ${s.pgProgress}/4. Time the next SPACE press in the green zone.`);tone("kick",props.muted);if(s.pgProgress>=4)finish();}else{props.onMessage("Almost! Wait until the swing meter reaches the green zone, then press SPACE.");}}else if(close&&s.playground===1&&action.current){s.pgProgress=Math.min(100,s.pgProgress+40*dt);if(s.pgProgress>=100){action.current=false;finish();}}else if(close&&s.playground===2){const dir=keys.current.has("arrowleft")||keys.current.has("a")?-1:keys.current.has("arrowright")||keys.current.has("d")?1:0;if(dir&&dir!==s.pgLast&&s.pgCooldown<=0){s.pgLast=dir;s.pgCooldown=.16;s.pgProgress++;tone("kick",props.muted);props.onMessage(`Seesaw rhythm ${s.pgProgress}/6 — alternate LEFT and RIGHT!`);if(s.pgProgress>=6)finish();}}else if(close&&s.playground===3&&action.current){action.current=false;const grip=(Math.sin(s.elapsed*4)+1)/2;if(grip>.42&&grip<.62){s.pgProgress++;tone("kick",props.muted);props.onMessage(`Great grip! ${s.pgProgress}/4. Keep timing SPACE in the green zone.`);if(s.pgProgress>=4)finish();}else props.onMessage("The climbing hold slipped! Watch the moving marker and press SPACE in green.");}else if(close&&s.playground===4&&action.current){action.current=false;const rope=(Math.sin(s.elapsed*5.2)+1)/2;if(rope<.37){s.pgProgress++;tone("kick",props.muted);props.onMessage(`Clean rope jump! ${s.pgProgress}/5.`);if(s.pgProgress>=5)finish();}else props.onMessage("The rope caught your feet! Press SPACE when the marker enters green.");}}
    else if(props.mode==="cycling"){movement(dt,300);const cps=[[150,130],[810,130],[810,480],[150,480]];const cp=cps[s.checkpoint];if(cp&&Math.hypot(s.px-cp[0],s.py-cp[1])<75){s.checkpoint++;props.onScore(125);tone("score",props.muted);if(s.checkpoint>=4)props.onComplete("cycling",{cyclingTime:Math.round(s.elapsed)});}}
    else if(props.mode==="championship"){s.championCooldown=Math.max(0,s.championCooldown-dt);const required=[3,3,5,8,4];const finish=()=>{props.onScore(400);tone("score",props.muted);s.championRound++;s.championProgress=0;s.championLast=0;s.championCooldown=.35;props.onMessage(`Championship trial ${s.championRound} won! ${s.championRound<5?"Get ready — the next challenge is faster.":"All five trials complete. Time for your champion interview!"}`);if(s.championRound>=5)setTimeout(()=>props.onInterview(),650);};if(s.championRound===3){const dir=keys.current.has("arrowleft")||keys.current.has("a")?-1:keys.current.has("arrowright")||keys.current.has("d")?1:0;if(dir&&dir!==s.championLast&&s.championCooldown<=0){s.championLast=dir;s.championCooldown=.13;s.championProgress++;tone("kick",props.muted);props.onMessage(`Sprint step ${s.championProgress}/8 — alternate LEFT and RIGHT!`);if(s.championProgress>=required[3])finish();}}else if(s.championRound<5&&action.current){action.current=false;const cursor=(Math.sin(s.elapsed*(2.7+s.championRound*.55))+1)/2;const hit=cursor>.42&&cursor<.62;if(hit){s.championProgress++;tone("kick",props.muted);props.onMessage(`Perfect timing! ${s.championProgress}/${required[s.championRound]} successful actions.`);if(s.championProgress>=required[s.championRound])finish();}else{s.championMisses++;props.onMessage("Missed! Watch the moving marker and press SPACE inside the green target.");}}}
  }
  function toneNumber(){return Math.random()*35;}
  function draw(ctx:CanvasRenderingContext2D){ctx.clearRect(0,0,960,600);if(props.mode==="park")drawPark(ctx,state.current,nearby.current,props.medals);else if(props.mode==="football")drawFootball(ctx,state.current);else if(props.mode==="basketball")drawBasketball(ctx,state.current);else if(props.mode==="badminton")drawBadminton(ctx,state.current);else if(props.mode==="running")drawRunning(ctx,state.current);else if(props.mode==="playground")drawPlayground(ctx,state.current);else if(props.mode==="cycling")drawCycling(ctx,state.current);else drawChampionship(ctx,state.current);}
  return <canvas ref={canvasRef} width={960} height={600} className="block aspect-[16/10] w-full bg-slate-900" aria-label={`${props.mode} action game canvas`} tabIndex={0}/>;
});

function drawPark(ctx:CanvasRenderingContext2D,s:Record<string,number>,near:ActivityId|"arena"|"interview"|null,medals:ActivityId[]){ctx.fillStyle="#86d15c";ctx.fillRect(0,0,960,600);ctx.fillStyle="#d1d5db";ctx.fillRect(0,260,960,70);ctx.fillRect(445,0,70,600);zone(ctx,35,45,230,180,"FOOTBALL","#16a34a",near==="football");zone(ctx,325,45,230,180,"BASKETBALL","#ea580c",near==="basketball");zone(ctx,615,45,230,180,"BADMINTON","#7c3aed",near==="badminton");zone(ctx,35,365,230,180,"RUNNING TRACK","#dc2626",near==="running");zone(ctx,325,365,230,180,"PLAYGROUND","#0891b2",near==="playground");zone(ctx,615,365,230,180,"CYCLING","#2563eb",near==="cycling");ctx.fillStyle=medals.length>=4?"#facc15":"#475569";ctx.fillRect(850,205,105,160);ctx.fillStyle="#0f172a";ctx.font="bold 12px sans-serif";ctx.textAlign="center";ctx.fillText(medals.length>=4?"ARENA OPEN":"ARENA LOCKED",902,250);ctx.fillText(medals.length>=4?"SPACE":"4 MEDALS",902,270);ctx.fillStyle="#fff";ctx.fillRect(8,235,110,120);ctx.fillStyle="#2563eb";ctx.fillRect(18,245,90,100);ctx.fillStyle="#fff";ctx.font="bold 11px sans-serif";ctx.fillText("INTERVIEW",63,275);drawPlayer(ctx,s.px,s.py,"walk");if(near){ctx.fillStyle="#0f172a";roundRect(ctx,350,545,260,38,18);ctx.fill();ctx.fillStyle="white";ctx.font="bold 15px sans-serif";ctx.fillText("SPACE · ENTER ACTIVITY",480,570);}}
function zone(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,label:string,color:string,active:boolean){ctx.fillStyle=color;roundRect(ctx,x,y,w,h,18);ctx.fill();ctx.strokeStyle=active?"#facc15":"rgba(255,255,255,.65)";ctx.lineWidth=active?8:3;ctx.stroke();ctx.fillStyle="rgba(255,255,255,.92)";ctx.fillRect(x+18,y+16,w-36,35);ctx.fillStyle="#0f172a";ctx.font="bold 14px sans-serif";ctx.textAlign="center";ctx.fillText(label,x+w/2,y+40);}
function drawFootball(ctx:CanvasRenderingContext2D,s:Record<string,number>){ctx.fillStyle="#16a34a";ctx.fillRect(0,0,960,600);ctx.strokeStyle="white";ctx.lineWidth=5;ctx.strokeRect(80,45,800,510);ctx.strokeRect(350,40,260,105);ctx.fillStyle="#f8fafc";ctx.fillRect(355,25,250,20);for(let x=355;x<605;x+=25){ctx.strokeStyle="#94a3b8";ctx.beginPath();ctx.moveTo(x,25);ctx.lineTo(x,145);ctx.stroke();}ctx.fillStyle="#ef4444";ctx.fillRect(430+Math.sin(s.elapsed*2)*90,55,55,22);drawBall(ctx,s.bx,s.by,"#fff");drawPlayer(ctx,s.px,s.py,"kick");scoreText(ctx,`GOALS ${s.scored}/3 · ROUND ${Math.min(3,s.round)}`);}
function drawBasketball(ctx:CanvasRenderingContext2D,s:Record<string,number>){ctx.fillStyle="#f97316";ctx.fillRect(0,0,960,600);ctx.strokeStyle="#fff";ctx.lineWidth=4;ctx.strokeRect(70,45,820,510);ctx.beginPath();ctx.arc(480,300,90,0,Math.PI*2);ctx.stroke();ctx.fillStyle="#fff";ctx.fillRect(430,110,100,12);ctx.strokeStyle="#ef4444";ctx.lineWidth=8;ctx.beginPath();ctx.arc(480,160,38,0,Math.PI);ctx.stroke();drawBall(ctx,s.bx,s.by,"#fb923c");drawPlayer(ctx,s.px,490,"throw");ctx.fillStyle="#0f172a";ctx.fillRect(330,540,300,25);ctx.fillStyle="#facc15";ctx.fillRect(330,540,s.power*3,25);scoreText(ctx,`BASKETS ${s.scored}/3 · HOLD SPACE FOR POWER`);}
function drawBadminton(ctx:CanvasRenderingContext2D,s:Record<string,number>){ctx.fillStyle="#7c3aed";ctx.fillRect(0,0,960,600);ctx.strokeStyle="#fff";ctx.lineWidth=4;ctx.strokeRect(60,55,840,500);ctx.fillRect(475,80,10,450);ctx.fillStyle="#f8fafc";ctx.beginPath();ctx.arc(s.bx,s.by,10,0,Math.PI*2);ctx.fill();ctx.strokeStyle="#f8fafc";ctx.beginPath();ctx.moveTo(s.bx,s.by);ctx.lineTo(s.bx-10,s.by-18);ctx.lineTo(s.bx+10,s.by-18);ctx.closePath();ctx.stroke();drawPlayer(ctx,s.px,515,"hit");drawPlayer(ctx,480,115,"hit");scoreText(ctx,`RALLY ${s.rally} · TARGET 8`);}
function drawRunning(ctx:CanvasRenderingContext2D,s:Record<string,number>){ctx.fillStyle="#dc2626";ctx.fillRect(0,0,960,600);for(let y=120;y<540;y+=105){ctx.strokeStyle="#fff";ctx.lineWidth=3;ctx.setLineDash([25,20]);ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(960,y);ctx.stroke();}ctx.setLineDash([]);const offset=s.distance%350;for(let x=300-offset;x<1100;x+=350){ctx.fillStyle="#facc15";ctx.beginPath();ctx.moveTo(x,470);ctx.lineTo(x+25,410);ctx.lineTo(x+50,470);ctx.closePath();ctx.fill();}drawPlayer(ctx,130,s.py,"run");scoreText(ctx,`RUN! · SPACE TO JUMP · ${Math.min(100,Math.round(s.distance/15))}%`);}
function drawPlayground(ctx:CanvasRenderingContext2D,s:Record<string,number>){ctx.fillStyle="#7dd3fc";ctx.fillRect(0,0,960,600);ctx.fillStyle="#fde68a";ctx.fillRect(0,330,960,270);const labels=["SWING","SLIDE","SEESAW","CLIMB","SKIPPING ROPE"];const pts=[[150,180],[330,180],[510,180],[690,180],[810,390]];pts.forEach((p,i)=>{ctx.fillStyle=i<s.playground?"#22c55e":i===s.playground?"#2563eb":"#64748b";roundRect(ctx,p[0]-60,p[1]-45,120,90,18);ctx.fill();if(i===s.playground){ctx.strokeStyle="#facc15";ctx.lineWidth=6;ctx.stroke();}ctx.fillStyle="white";ctx.font="bold 12px sans-serif";ctx.textAlign="center";ctx.fillText(i<s.playground?"✓ "+labels[i]:labels[i],p[0],p[1]+5);});const instructions=["Time SPACE in green · 4 pumps","Hold SPACE to climb and slide","Alternate LEFT / RIGHT · 6 steps","Time SPACE in green · 4 grips","Time SPACE in green · 5 jumps"];if(s.playground<5){ctx.fillStyle="rgba(15,23,42,.9)";roundRect(ctx,210,515,540,58,18);ctx.fill();ctx.fillStyle="#facc15";ctx.font="bold 17px sans-serif";ctx.textAlign="center";ctx.fillText(instructions[s.playground],480,542);const isMeter=[0,3,4].includes(s.playground);if(isMeter){const cursor=(Math.sin(s.elapsed*(s.playground===4?5.2:s.playground===3?4:3.1))+1)/2;ctx.fillStyle="#475569";ctx.fillRect(330,552,300,10);ctx.fillStyle="#22c55e";const greenX=s.playground===4?330:456;const greenW=s.playground===4?111:60;ctx.fillRect(greenX,552,greenW,10);ctx.fillStyle="#fff";ctx.fillRect(330+cursor*294,548,6,18);}}drawPlayer(ctx,s.px,s.py,"jump");scoreText(ctx,`STATION ${Math.min(5,s.playground+1)}/5 · PROGRESS ${Math.round(s.pgProgress)}`);}
function drawCycling(ctx:CanvasRenderingContext2D,s:Record<string,number>){ctx.fillStyle="#22c55e";ctx.fillRect(0,0,960,600);ctx.strokeStyle="#64748b";ctx.lineWidth=80;roundRect(ctx,100,85,760,430,80);ctx.stroke();ctx.strokeStyle="#facc15";ctx.lineWidth=4;ctx.setLineDash([20,16]);roundRect(ctx,100,85,760,430,80);ctx.stroke();ctx.setLineDash([]);[[150,130],[810,130],[810,480],[150,480]].forEach((p,i)=>{ctx.fillStyle=i<s.checkpoint?"#22c55e":"#fff";ctx.beginPath();ctx.arc(p[0],p[1],24,0,Math.PI*2);ctx.fill();ctx.fillStyle="#0f172a";ctx.font="bold 15px sans-serif";ctx.textAlign="center";ctx.fillText(String(i+1),p[0],p[1]+5);});drawBike(ctx,s.px,s.py);scoreText(ctx,`CHECKPOINT ${s.checkpoint}/4 · RIDE!`);}
function drawChampionship(ctx:CanvasRenderingContext2D,s:Record<string,number>){ctx.fillStyle="#0f172a";ctx.fillRect(0,0,960,600);ctx.fillStyle="#1e3a8a";ctx.fillRect(35,40,890,510);const labels=["POWER KICK","BASKET THROW","RALLY HIT","SPRINT STEPS","ROPE JUMP"];const required=[3,3,5,8,4];for(let i=0;i<5;i++){ctx.fillStyle=i<s.championRound?"#22c55e":i===s.championRound?"#facc15":"#334155";ctx.beginPath();ctx.arc(180+i*150,125,48,0,Math.PI*2);ctx.fill();ctx.fillStyle=i===s.championRound?"#0f172a":"white";ctx.font="bold 12px sans-serif";ctx.textAlign="center";ctx.fillText(i<s.championRound?"✓":String(i+1),180+i*150,130);}ctx.fillStyle="white";ctx.font="bold 30px sans-serif";ctx.fillText(labels[Math.min(4,s.championRound)],480,230);ctx.font="bold 18px sans-serif";ctx.fillStyle="#bfdbfe";ctx.fillText(s.championRound===3?"Alternate LEFT and RIGHT as fast as you can!":"Press SPACE only when the marker is inside green!",480,268);ctx.fillStyle="#334155";roundRect(ctx,180,315,600,48,20);ctx.fill();if(s.championRound!==3){ctx.fillStyle="#22c55e";ctx.fillRect(432,315,120,48);const cursor=(Math.sin(s.elapsed*(2.7+s.championRound*.55))+1)/2;ctx.fillStyle="#fff";ctx.fillRect(180+cursor*590,306,10,66);}ctx.fillStyle="#facc15";ctx.font="bold 24px sans-serif";ctx.fillText(`${Math.round(s.championProgress)} / ${required[Math.min(4,s.championRound)]}`,480,420);ctx.fillStyle="#fca5a5";ctx.font="bold 14px sans-serif";ctx.fillText(`MISSES ${s.championMisses}`,480,452);drawPlayer(ctx,480,500,"run");scoreText(ctx,`SPORTS CHAMPIONSHIP · TRIAL ${Math.min(5,s.championRound+1)}/5`);}
function scoreText(ctx:CanvasRenderingContext2D,text:string){ctx.fillStyle="rgba(15,23,42,.88)";roundRect(ctx,230,18,500,46,20);ctx.fill();ctx.fillStyle="white";ctx.font="bold 18px sans-serif";ctx.textAlign="center";ctx.fillText(text,480,48);}
function drawPlayer(ctx:CanvasRenderingContext2D,x:number,y:number,pose:string){ctx.save();ctx.translate(x,y);ctx.strokeStyle="#172554";ctx.lineWidth=10;ctx.lineCap="round";ctx.beginPath();ctx.moveTo(-8,12);ctx.lineTo(pose==="run"?-18:-9,34);ctx.moveTo(8,12);ctx.lineTo(pose==="run"?21:9,34);ctx.stroke();ctx.fillStyle="#2563eb";roundRect(ctx,-18,-24,36,45,10);ctx.fill();ctx.fillStyle="#f2c9a5";ctx.beginPath();ctx.arc(0,-39,17,0,Math.PI*2);ctx.fill();ctx.fillStyle="#172554";ctx.beginPath();ctx.arc(0,-44,17,Math.PI,Math.PI*2);ctx.fill();ctx.fillStyle="white";ctx.font="bold 9px sans-serif";ctx.textAlign="center";ctx.fillText("LEAD",0,2);ctx.restore();}
function drawBike(ctx:CanvasRenderingContext2D,x:number,y:number){ctx.strokeStyle="#0f172a";ctx.lineWidth=5;ctx.beginPath();ctx.arc(x-20,y+15,14,0,Math.PI*2);ctx.arc(x+20,y+15,14,0,Math.PI*2);ctx.moveTo(x-20,y+15);ctx.lineTo(x,y-8);ctx.lineTo(x+20,y+15);ctx.lineTo(x-5,y+15);ctx.closePath();ctx.stroke();drawPlayer(ctx,x,y-25,"ride");}
function drawBall(ctx:CanvasRenderingContext2D,x:number,y:number,color:string){ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,y,15,0,Math.PI*2);ctx.fill();ctx.strokeStyle="#0f172a";ctx.lineWidth=2;ctx.stroke();}
function roundRect(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,r:number){ctx.beginPath();ctx.roundRect(x,y,w,h,r);}

function Start({ onStart }: { onStart: (name:string)=>void }) { const [value,setValue]=useState(""); return <section className="relative overflow-hidden rounded-[32px] bg-[radial-gradient(circle_at_80%_15%,#facc15_0_4%,transparent_22%),linear-gradient(145deg,#dbeafe,#fff_55%,#dcfce7)] p-7 shadow-soft sm:p-11"><div className="mx-auto grid max-w-5xl items-center gap-8 lg:grid-cols-[1.15fr_.85fr]"><div><p className="text-sm font-black uppercase tracking-[.2em] text-lead-blue">LEAD · Learn English Daily</p><h2 className="mt-4 font-heading text-5xl font-black leading-[1.04] text-lead-navy sm:text-6xl">Playground<br/><span className="text-lead-blue">Champions</span></h2><p className="mt-4 text-2xl font-black text-amber-600">Play. Speak. Become a Champion!</p><div className="relative mt-7 h-56 overflow-hidden rounded-3xl bg-[linear-gradient(#7dd3fc_0_55%,#22c55e_55%)]"><div className="absolute bottom-7 left-8 h-20 w-36 rounded-t-full border-8 border-white bg-green-600"/><div className="absolute bottom-8 right-10 h-28 w-28 rounded-full border-[14px] border-orange-500 bg-orange-200"/><div className="absolute left-1/2 top-12 -translate-x-1/2"><ChampionArt/></div></div></div><form onSubmit={(e)=>{e.preventDefault();if(value.trim())onStart(value.trim().slice(0,24));}} className="rounded-3xl border-2 border-white bg-white/90 p-6 shadow-xl"><div className="mx-auto grid h-20 w-20 place-items-center rounded-full bg-yellow-100"><Trophy className="h-11 w-11 text-amber-600"/></div><h3 className="mt-4 text-center font-heading text-2xl font-black text-lead-navy">Welcome, Champion!</h3><label className="mt-6 block text-sm font-black uppercase tracking-widest text-lead-blue">What&apos;s your name?</label><input autoFocus value={value} onChange={(e)=>setValue(e.target.value)} placeholder="Enter your name" className="focus-ring mt-3 h-14 w-full rounded-xl border-2 border-blue-100 px-4 text-lg font-bold text-lead-navy"/><Button type="submit" size="lg" className="mt-4 w-full" disabled={!value.trim()}><Trophy className="h-5 w-5"/>Enter Sports Park</Button></form></div></section>; }
function Interview({ name,played,favorite,setFavorite,reason,setReason,spoken,setSpoken,muted,onComplete }: { name:string;played:ActivityId[];favorite:ActivityId;setFavorite:(id:ActivityId)=>void;reason:string;setReason:(r:string)=>void;spoken:boolean;setSpoken:(v:boolean)=>void;muted:boolean;onComplete:()=>void }) { const options=played.length?played:["football" as ActivityId]; const sentence=`My favorite sport is ${activityData[favorite].name.toLowerCase()} because ${reason}.`; return <section className="mx-auto max-w-4xl"><Wisey>{name}, you played {options.length} activities today! Now the reporter wants your champion story.</Wisey><div className="mt-5 grid gap-6 rounded-3xl bg-[linear-gradient(145deg,#1e3a8a,#0f172a)] p-6 text-white lg:grid-cols-[.75fr_1.25fr]"><div className="rounded-3xl bg-white/10 p-5 text-center"><Mic className="mx-auto h-14 w-14 text-yellow-300"/><h2 className="mt-3 font-heading text-3xl font-black">Champion Interview</h2><ChampionArt/><p className="mt-3 text-sm text-blue-100">Reporter: “What is your favorite sport, {name}?”</p></div><div><p className="text-xs font-black uppercase tracking-widest text-yellow-300">1 · Choose your sport</p><div className="mt-2 flex flex-wrap gap-2">{options.map(id=><button key={id} onClick={()=>{setFavorite(id);setSpoken(false);}} className={`focus-ring rounded-xl px-4 py-3 text-sm font-black ${favorite===id?"bg-yellow-300 text-lead-navy":"bg-white/10"}`}>{activityData[id].name}</button>)}</div><p className="mt-5 text-xs font-black uppercase tracking-widest text-yellow-300">2 · Why do you like it?</p><select value={reason} onChange={(e)=>{setReason(e.target.value);setSpoken(false);}} className="focus-ring mt-2 h-12 w-full rounded-xl bg-white px-3 font-bold text-lead-navy"><option value="it is fun">It is fun.</option><option value="I like playing with my friends">I like playing with my friends.</option><option value="I like running">I like running.</option><option value="I like scoring goals">I like scoring goals.</option><option value="I like being active">I like being active.</option></select><div className="mt-5 rounded-2xl bg-white/10 p-5"><p className="text-sm font-bold text-blue-100">YOUR CHALLENGE SENTENCE</p><p className="mt-2 text-2xl font-black leading-9">“{sentence}”</p><p className="mt-3 text-sm">Normal: “I play {activityData[favorite].name.toLowerCase()} in the playground.”</p></div><div className="mt-4 grid grid-cols-2 gap-3"><Button variant="secondary" onClick={()=>say(sentence,muted)}><Volume2 className="h-4 w-4"/>Listen</Button><Button onClick={()=>setSpoken(true)} className={spoken?"bg-emerald-600":""}><Mic className="h-4 w-4"/>{spoken?"Great speaking!":"I said it!"}</Button></div>{spoken?<Button onClick={onComplete} className="mt-3 w-full">See Champion Results <Trophy className="h-4 w-4"/></Button>:null}</div></div></section>; }
function Results({ name,medals,stats,favorite,onReplay,onExplore,onChange }: { name:string;medals:ActivityId[];stats:Stats;favorite:ActivityId;onReplay:()=>void;onExplore:()=>void;onChange:()=>void }) { return <section className="mx-auto max-w-5xl text-center"><div className="mx-auto grid h-24 w-24 place-items-center rounded-full bg-yellow-100"><Trophy className="h-14 w-14 text-amber-600"/></div><p className="mt-5 text-sm font-black uppercase tracking-[.2em] text-lead-blue">Playground Champion!</p><h2 className="mt-2 font-heading text-5xl font-black text-lead-navy">Great job, {name}!</h2><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Result label="Score" value={stats.score.toLocaleString()}/><Result label="Medals" value={String(medals.length)}/><Result label="Football Goals" value={String(stats.goals)}/><Result label="Baskets" value={String(stats.baskets)}/><Result label="Best Rally" value={String(stats.bestRally)}/><Result label="Race Time" value={stats.raceTime?`${stats.raceTime}s`:"—"}/><Result label="Stars" value={String(stats.stars)}/><Result label="Cycling Time" value={stats.cyclingTime?`${stats.cyclingTime}s`:"—"}/></div><div className="mt-6 rounded-3xl bg-lead-navy p-7 text-white"><p className="text-xs font-black uppercase tracking-widest text-yellow-300">My favorite sport</p><p className="mt-2 font-heading text-4xl font-black">{activityData[favorite].name}</p><p className="mt-3 text-2xl font-bold">“I play {activityData[favorite].name.toLowerCase()} in the playground.”</p></div><div className="mt-7 flex flex-wrap justify-center gap-3"><Button onClick={onReplay}><RotateCcw className="h-4 w-4"/>Play Again</Button><Button variant="secondary" onClick={onExplore}><ArrowRight className="h-4 w-4"/>Explore Park</Button><Button variant="secondary" onClick={onChange}><UserRound className="h-4 w-4"/>Change Student</Button></div><p className="mt-8 font-black text-lead-blue">LEAD · Learn English Daily</p><p className="text-sm font-bold text-lead-gray">Speak English with Confidence</p></section>; }
function controlHint(id:ActivityId){return id==="football"?"Run to the ball, aim, and press SPACE to kick.":id==="basketball"?"Move into position. Hold SPACE for power; release to shoot.":id==="badminton"?"Move left and right. Press SPACE as the shuttle reaches you.":id==="running"?"Hold RIGHT to run fast. Press SPACE to jump over cones.":id==="playground"?"Master five different stations: timing, climbing, rhythm, grip, and jumping.":"Ride with WASD or Arrow Keys and reach four checkpoints.";}
function Wisey({children}:{children:React.ReactNode}){return <div className="flex items-center gap-3 rounded-2xl border border-yellow-200 bg-yellow-50 p-4"><div className="grid h-14 w-14 shrink-0 place-items-center rounded-full bg-lead-blue text-xl font-black text-white">W</div><p className="text-sm font-bold leading-6 text-lead-navy">{children}</p></div>;}
function Card({title,children}:{title:string;children:React.ReactNode}){return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><p className="mb-2 text-xs font-black uppercase tracking-widest text-lead-blue">{title}</p>{children}</div>;}
function Result({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-blue-100 bg-blue-50 p-4"><p className="font-heading text-3xl font-black text-lead-blue">{value}</p><p className="mt-1 text-xs font-black uppercase text-lead-navy">{label}</p></div>;}
function ChampionArt(){return <svg viewBox="0 0 120 170" className="mx-auto mt-3 w-28"><circle cx="60" cy="32" r="25" fill="#f2c9a5"/><path d="M35 29Q39 4 65 7Q88 10 84 34" fill="#172554"/><rect x="30" y="58" width="60" height="67" rx="18" fill="#2563eb"/><text x="60" y="95" textAnchor="middle" fill="white" fontSize="16" fontWeight="900">LEAD</text><path d="M37 120L31 163M82 120L89 163" stroke="#0f172a" strokeWidth="14" strokeLinecap="round"/><path d="M31 75L9 45M89 75L111 45" stroke="#f2c9a5" strokeWidth="11" strokeLinecap="round"/><path d="M45 42Q60 52 74 42" fill="none" stroke="#9f503b" strokeWidth="3"/></svg>;}
function TouchControls({refHandle}:{refHandle:React.RefObject<GameCanvasHandle|null>}){const cls="focus-ring grid h-10 w-10 place-items-center rounded-lg bg-lead-navy text-white";function tap(key:string){refHandle.current?.direction(key,true);window.setTimeout(()=>refHandle.current?.direction(key,false),140);}function releaseAction(){window.setTimeout(()=>refHandle.current?.action(false),90);}return <div className="mt-3 grid grid-cols-3 gap-1"><span/><button aria-label="Move up" className={cls} onClick={()=>tap("arrowup")}><ArrowUp className="h-4 w-4"/></button><span/><button aria-label="Move left" className={cls} onClick={()=>tap("arrowleft")}><ArrowLeft className="h-4 w-4"/></button><button aria-label="Action" className="focus-ring grid h-10 w-10 place-items-center rounded-lg bg-yellow-400 text-lead-navy" onPointerDown={()=>refHandle.current?.action(true)} onPointerUp={releaseAction} onPointerCancel={releaseAction}><Star className="h-4 w-4"/></button><button aria-label="Move right" className={cls} onClick={()=>tap("arrowright")}><ArrowRight className="h-4 w-4"/></button><span/><button aria-label="Move down" className={cls} onClick={()=>tap("arrowdown")}><ArrowDown className="h-4 w-4"/></button><span/></div>;}
